// GENERATED by app/shared/scripts/build-app-tokens.mjs from figma-variables.json — do not edit.
// Fix values in the Figma variables and export again (APP.md §8).

import SwiftUI

public enum DSTokens {
    public enum Color {
        /// color/text/primary — Primary text such as page headings, table cell values and body copy.
        public static let textPrimary = DSColor(light: 0xFF0F172A, dark: 0xFFF8FAFC)
        /// color/text/primary/on-brand — Primary text on solid brand surfaces, such as a brand-colored banner heading.
        public static let textPrimaryOnBrand = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// color/text/secondary — Secondary text such as labels, section headings and navigation items.
        public static let textSecondary = DSColor(light: 0xFF334155, dark: 0xFFCBD5E1)
        /// color/text/secondary/hover — Secondary text in hover states, such as a navigation item under the pointer.
        public static let textSecondaryHover = DSColor(light: 0xFF1E293B, dark: 0xFFE2E8F0)
        /// color/text/secondary/on-brand — Secondary text on solid brand surfaces.
        public static let textSecondaryOnBrand = DSColor(light: 0xFFDBEAFE, dark: 0xFFDBEAFE)
        /// color/text/tertiary — Supporting text such as descriptions, timestamps and helper copy.
        public static let textTertiary = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// color/text/tertiary/hover — Supporting text in hover states, such as a breadcrumb link.
        public static let textTertiaryHover = DSColor(light: 0xFF334155, dark: 0xFFCBD5E1)
        /// color/text/tertiary/on-brand — Supporting text on solid brand surfaces.
        public static let textTertiaryOnBrand = DSColor(light: 0xFFBFDBFE, dark: 0xFFBFDBFE)
        /// color/text/disabled — Text in disabled controls and unavailable menu items.
        public static let textDisabled = DSColor(light: 0xFF94A3B8, dark: 0xFF475569)
        /// color/text/placeholder — Placeholder and empty-input hint text.
        public static let textPlaceholder = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// color/text/inverse — Text on inverse surfaces such as tooltips.
        public static let textInverse = DSColor(light: 0xFFFFFFFF, dark: 0xFF0F172A)
        /// color/text/on-solid — Text on any solid tone fill: primary buttons, solid badges, danger buttons.
        public static let textOnSolid = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// color/text/brand — Brand-colored text such as links and highlighted figures.
        public static let textBrand = DSColor(light: 0xFF1D4ED8, dark: 0xFF93C5FD)
        /// color/text/brand/hover — Links and brand text under the pointer.
        public static let textBrandHover = DSColor(light: 0xFF1E40AF, dark: 0xFFBFDBFE)
        /// color/text/brand/pressed — Links and brand text while pressed.
        public static let textBrandPressed = DSColor(light: 0xFF1E3A8A, dark: 0xFFDBEAFE)
        /// color/text/danger — Error messages and danger text, such as an invalid-field message.
        public static let textDanger = DSColor(light: 0xFF991B1B, dark: 0xFFFECACA)
        /// color/text/warning — Warning messages and caution labels.
        public static let textWarning = DSColor(light: 0xFFB45309, dark: 0xFFFCD34D)
        /// color/text/success — Success messages and positive values.
        public static let textSuccess = DSColor(light: 0xFF15803D, dark: 0xFF86EFAC)
        /// color/text/info — Informational messages and neutral notices.
        public static let textInfo = DSColor(light: 0xFF0369A1, dark: 0xFF7DD3FC)
        /// color/icon/primary — Icons that carry the main meaning of a row or control.
        public static let iconPrimary = DSColor(light: 0xFF1E293B, dark: 0xFFF1F5F9)
        /// color/icon/primary/on-brand — Primary icons on solid brand surfaces.
        public static let iconPrimaryOnBrand = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// color/icon/secondary — Icons in buttons, inputs and menu items.
        public static let iconSecondary = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// color/icon/secondary/hover — Icons in those controls under the pointer.
        public static let iconSecondaryHover = DSColor(light: 0xFF334155, dark: 0xFFCBD5E1)
        /// color/icon/secondary/on-brand — Secondary icons on solid brand surfaces.
        public static let iconSecondaryOnBrand = DSColor(light: 0xFFBFDBFE, dark: 0xFFBFDBFE)
        /// color/icon/tertiary — Supporting icons such as a chevron in a list row or a metadata icon.
        public static let iconTertiary = DSColor(light: 0xFF64748B, dark: 0xFF64748B)
        /// color/icon/tertiary/hover — Supporting icons under the pointer, such as a help icon on hover.
        public static let iconTertiaryHover = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// color/icon/tertiary/on-brand — Supporting icons on solid brand surfaces.
        public static let iconTertiaryOnBrand = DSColor(light: 0xFF93C5FD, dark: 0xFF93C5FD)
        /// color/icon/disabled — Icons in disabled controls.
        public static let iconDisabled = DSColor(light: 0xFFCBD5E1, dark: 0xFF334155)
        /// color/icon/placeholder — Leading icons inside empty inputs, such as a search icon.
        public static let iconPlaceholder = DSColor(light: 0xFF94A3B8, dark: 0xFF475569)
        /// color/icon/inverse — Icons on inverse surfaces such as tooltips.
        public static let iconInverse = DSColor(light: 0xFFFFFFFF, dark: 0xFF0F172A)
        /// color/icon/on-solid — Icons on solid tone fills, such as the icon in a primary button.
        public static let iconOnSolid = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// color/icon/brand — Brand icons such as a selected navigation icon or an active tab icon.
        public static let iconBrand = DSColor(light: 0xFF2563EB, dark: 0xFF60A5FA)
        /// color/icon/brand/hover — Brand icons under the pointer.
        public static let iconBrandHover = DSColor(light: 0xFF1D4ED8, dark: 0xFF93C5FD)
        /// color/icon/brand/pressed — Brand icons while pressed.
        public static let iconBrandPressed = DSColor(light: 0xFF1E40AF, dark: 0xFFBFDBFE)
        /// color/icon/danger — Error icons in alerts, fields and featured icons.
        public static let iconDanger = DSColor(light: 0xFFDC2626, dark: 0xFFEF4444)
        /// color/icon/warning — Warning icons; also the filled part of rating stars.
        public static let iconWarning = DSColor(light: 0xFFD97706, dark: 0xFFF59E0B)
        /// color/icon/success — Success icons, online dots and positive trend arrows.
        public static let iconSuccess = DSColor(light: 0xFF16A34A, dark: 0xFF22C55E)
        /// color/icon/info — Informational icons.
        public static let iconInfo = DSColor(light: 0xFF0284C7, dark: 0xFF0EA5E9)
        /// color/border/subtle — Dividers, table rows and the outline of cards and menus.
        public static let borderSubtle = DSColor(light: 0xFFE2E8F0, dark: 0xFF1E293B)
        /// color/border/default — Default border around form controls, checkboxes and secondary buttons.
        public static let borderDefault = DSColor(light: 0xFFCBD5E1, dark: 0xFF334155)
        /// color/border/strong — Borders that must stand out, such as a control boundary on a tinted surface or a hovered input.
        public static let borderStrong = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// color/border/brand — Selected controls and active inputs, such as a selected choice card or a focused field.
        public static let borderBrand = DSColor(light: 0xFF2563EB, dark: 0xFF60A5FA)
        /// color/border/brand/subtle — Brand-tinted outlines, such as a brand badge border.
        public static let borderBrandSubtle = DSColor(light: 0xFF93C5FD, dark: 0xFF1E40AF)
        /// color/border/danger — Border of an invalid field.
        public static let borderDanger = DSColor(light: 0xFFDC2626, dark: 0xFFF87171)
        /// color/border/danger/subtle — Outline of danger badges and error alerts.
        public static let borderDangerSubtle = DSColor(light: 0xFFFCA5A5, dark: 0xFF991B1B)
        /// color/border/warning — Border of a field with a warning.
        public static let borderWarning = DSColor(light: 0xFFF59E0B, dark: 0xFFFBBF24)
        /// color/border/warning/subtle — Outline of warning badges and alerts.
        public static let borderWarningSubtle = DSColor(light: 0xFFFCD34D, dark: 0xFF92400E)
        /// color/border/success — Border of a validated field.
        public static let borderSuccess = DSColor(light: 0xFF16A34A, dark: 0xFF4ADE80)
        /// color/border/success/subtle — Outline of success badges and alerts.
        public static let borderSuccessSubtle = DSColor(light: 0xFF86EFAC, dark: 0xFF166534)
        /// color/border/info — Border of an informational field or callout.
        public static let borderInfo = DSColor(light: 0xFF0284C7, dark: 0xFF38BDF8)
        /// color/border/info/subtle — Outline of info badges and alerts.
        public static let borderInfoSubtle = DSColor(light: 0xFF7DD3FC, dark: 0xFF075985)
        /// color/border/focus — Focus ring color.
        public static let borderFocus = DSColor(light: 0xFF3B82F6, dark: 0xFF60A5FA)
        /// color/border/disabled — Borders of disabled controls.
        public static let borderDisabled = DSColor(light: 0xFFE2E8F0, dark: 0xFF1E293B)
        /// color/surface/base — Page background and the default background of cards and controls.
        public static let surfaceBase = DSColor(light: 0xFFFFFFFF, dark: 0xFF020617)
        /// color/surface/base/hover — Rows, list items and secondary buttons under the pointer.
        public static let surfaceBaseHover = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/surface/base/pressed — Rows, list items and secondary buttons while pressed.
        public static let surfaceBasePressed = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/surface/sunken — Recessed areas: page sections behind cards, table headers, code blocks.
        public static let surfaceSunken = DSColor(light: 0xFFF8FAFC, dark: 0xFF000000)
        /// color/surface/sunken/hover — Recessed rows under the pointer.
        public static let surfaceSunkenHover = DSColor(light: 0xFFF1F5F9, dark: 0xFF0F172A)
        /// color/surface/raised — Cards and panels that sit above the page; used with elevation/raised.
        public static let surfaceRaised = DSColor(light: 0xFFFFFFFF, dark: 0xFF0F172A)
        /// color/surface/raised/hover — Clickable cards under the pointer.
        public static let surfaceRaisedHover = DSColor(light: 0xFFF8FAFC, dark: 0xFF1E293B)
        /// color/surface/overlay — Menus, popovers, dialogs and drawers; used with elevation/overlay and elevation/modal.
        public static let surfaceOverlay = DSColor(light: 0xFFFFFFFF, dark: 0xFF1E293B)
        /// color/surface/inverse — Inverse surfaces such as tooltips and dark callouts.
        public static let surfaceInverse = DSColor(light: 0xFF0F172A, dark: 0xFFF8FAFC)
        /// color/surface/brand-subtle — Lightly tinted brand areas, such as a highlighted plan card or an announcement panel.
        public static let surfaceBrandSubtle = DSColor(light: 0xFFEFF6FF, dark: 0xFF172554)
        /// color/surface/brand-subtle/hover — Tinted brand areas under the pointer.
        public static let surfaceBrandSubtleHover = DSColor(light: 0xFFDBEAFE, dark: 0xFF1E3A8A)
        /// color/surface/brand-solid — Solid brand sections such as a marketing banner; content on it uses the on-brand roles.
        public static let surfaceBrandSolid = DSColor(light: 0xFF1D4ED8, dark: 0xFF1D4ED8)
        /// color/fill/neutral/solid — Solid neutral fill, such as solid neutral badges.
        public static let fillNeutralSolid = DSColor(light: 0xFF0F172A, dark: 0xFFF8FAFC)
        /// color/fill/neutral/solid/hover — The solid neutral fill under the pointer.
        public static let fillNeutralSolidHover = DSColor(light: 0xFF1E293B, dark: 0xFFF1F5F9)
        /// color/fill/neutral/solid/pressed — The solid neutral fill while pressed.
        public static let fillNeutralSolidPressed = DSColor(light: 0xFF334155, dark: 0xFFE2E8F0)
        /// color/fill/neutral/solid/selected — A selected solid neutral item.
        public static let fillNeutralSolidSelected = DSColor(light: 0xFF1E293B, dark: 0xFFF1F5F9)
        /// color/fill/neutral/solid/disabled — Solid neutral fills of disabled controls.
        public static let fillNeutralSolidDisabled = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/neutral/subtle — Tinted neutral fill: neutral badges, ghost-button hovers and selected rows in lists.
        public static let fillNeutralSubtle = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/neutral/subtle/hover — The tinted neutral fill under the pointer, such as a tertiary button or menu row hover.
        public static let fillNeutralSubtleHover = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/neutral/subtle/pressed — The tinted neutral fill while pressed.
        public static let fillNeutralSubtlePressed = DSColor(light: 0xFFE2E8F0, dark: 0xFF334155)
        /// color/fill/neutral/subtle/selected — Selected rows and selected neutral items, such as a chosen segment or command.
        public static let fillNeutralSubtleSelected = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/neutral/subtle/disabled — Tinted fills of disabled controls, such as a disabled input or primary button.
        public static let fillNeutralSubtleDisabled = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/brand/solid — Solid brand fill: primary buttons, checked checkboxes and radios, switches that are on and progress fills.
        public static let fillBrandSolid = DSColor(light: 0xFF2563EB, dark: 0xFF2563EB)
        /// color/fill/brand/solid/hover — The solid brand fill under the pointer.
        public static let fillBrandSolidHover = DSColor(light: 0xFF1D4ED8, dark: 0xFF1D4ED8)
        /// color/fill/brand/solid/pressed — The solid brand fill while pressed.
        public static let fillBrandSolidPressed = DSColor(light: 0xFF1E40AF, dark: 0xFF1E40AF)
        /// color/fill/brand/solid/selected — A selected solid brand item, such as the active segment of a segmented control.
        public static let fillBrandSolidSelected = DSColor(light: 0xFF1D4ED8, dark: 0xFF1D4ED8)
        /// color/fill/brand/solid/disabled — Solid brand fills of disabled controls.
        public static let fillBrandSolidDisabled = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/brand/subtle — Tinted brand fill: brand badges, highlighted options and selected brand rows.
        public static let fillBrandSubtle = DSColor(light: 0xFFEFF6FF, dark: 0xFF172554)
        /// color/fill/brand/subtle/hover — The tinted brand fill under the pointer.
        public static let fillBrandSubtleHover = DSColor(light: 0xFFDBEAFE, dark: 0xFF1E3A8A)
        /// color/fill/brand/subtle/pressed — The tinted brand fill while pressed.
        public static let fillBrandSubtlePressed = DSColor(light: 0xFFBFDBFE, dark: 0xFF1E40AF)
        /// color/fill/brand/subtle/selected — Selected rows and selected brand items, such as a chosen segment or command.
        public static let fillBrandSubtleSelected = DSColor(light: 0xFFDBEAFE, dark: 0xFF1E3A8A)
        /// color/fill/brand/subtle/disabled — Tinted fills of disabled controls, such as a disabled input or primary button.
        public static let fillBrandSubtleDisabled = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/danger/solid — Solid danger fill: danger buttons and destructive confirmations.
        public static let fillDangerSolid = DSColor(light: 0xFFDC2626, dark: 0xFFDC2626)
        /// color/fill/danger/solid/hover — The solid danger fill under the pointer.
        public static let fillDangerSolidHover = DSColor(light: 0xFFB91C1C, dark: 0xFFB91C1C)
        /// color/fill/danger/solid/pressed — The solid danger fill while pressed.
        public static let fillDangerSolidPressed = DSColor(light: 0xFF991B1B, dark: 0xFF991B1B)
        /// color/fill/danger/solid/selected — A selected solid danger item, such as the active segment of a segmented control.
        public static let fillDangerSolidSelected = DSColor(light: 0xFFB91C1C, dark: 0xFFB91C1C)
        /// color/fill/danger/solid/disabled — Solid danger fills of disabled controls.
        public static let fillDangerSolidDisabled = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/danger/subtle — Tinted danger fill: danger badges, error alert backgrounds and danger hovers.
        public static let fillDangerSubtle = DSColor(light: 0xFFFEF2F2, dark: 0xFF450A0A)
        /// color/fill/danger/subtle/hover — The tinted danger fill under the pointer, such as a tertiary button or menu row hover.
        public static let fillDangerSubtleHover = DSColor(light: 0xFFFEE2E2, dark: 0xFF7F1D1D)
        /// color/fill/danger/subtle/pressed — The tinted danger fill while pressed.
        public static let fillDangerSubtlePressed = DSColor(light: 0xFFFECACA, dark: 0xFF991B1B)
        /// color/fill/danger/subtle/selected — Selected rows and selected danger items, such as a chosen segment or command.
        public static let fillDangerSubtleSelected = DSColor(light: 0xFFFEE2E2, dark: 0xFF7F1D1D)
        /// color/fill/danger/subtle/disabled — Tinted fills of disabled controls, such as a disabled input or primary button.
        public static let fillDangerSubtleDisabled = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/warning/solid — Solid warning fill: solid warning badges and caution markers.
        public static let fillWarningSolid = DSColor(light: 0xFFD97706, dark: 0xFFD97706)
        /// color/fill/warning/solid/hover — The solid warning fill under the pointer.
        public static let fillWarningSolidHover = DSColor(light: 0xFFB45309, dark: 0xFFF59E0B)
        /// color/fill/warning/solid/pressed — The solid warning fill while pressed.
        public static let fillWarningSolidPressed = DSColor(light: 0xFF92400E, dark: 0xFFB45309)
        /// color/fill/warning/solid/selected — A selected solid warning item, such as the active segment of a segmented control.
        public static let fillWarningSolidSelected = DSColor(light: 0xFFB45309, dark: 0xFFF59E0B)
        /// color/fill/warning/solid/disabled — Solid warning fills of disabled controls.
        public static let fillWarningSolidDisabled = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/warning/subtle — Tinted warning fill: warning badges and warning alert backgrounds.
        public static let fillWarningSubtle = DSColor(light: 0xFFFFFBEB, dark: 0xFF451A03)
        /// color/fill/warning/subtle/hover — The tinted warning fill under the pointer, such as a tertiary button or menu row hover.
        public static let fillWarningSubtleHover = DSColor(light: 0xFFFEF3C7, dark: 0xFF78350F)
        /// color/fill/warning/subtle/pressed — The tinted warning fill while pressed.
        public static let fillWarningSubtlePressed = DSColor(light: 0xFFFDE68A, dark: 0xFF92400E)
        /// color/fill/warning/subtle/selected — Selected rows and selected warning items, such as a chosen segment or command.
        public static let fillWarningSubtleSelected = DSColor(light: 0xFFFEF3C7, dark: 0xFF78350F)
        /// color/fill/warning/subtle/disabled — Tinted fills of disabled controls, such as a disabled input or primary button.
        public static let fillWarningSubtleDisabled = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/success/solid — Solid success fill: solid success badges and completed-step markers.
        public static let fillSuccessSolid = DSColor(light: 0xFF16A34A, dark: 0xFF16A34A)
        /// color/fill/success/solid/hover — The solid success fill under the pointer.
        public static let fillSuccessSolidHover = DSColor(light: 0xFF15803D, dark: 0xFF22C55E)
        /// color/fill/success/solid/pressed — The solid success fill while pressed.
        public static let fillSuccessSolidPressed = DSColor(light: 0xFF166534, dark: 0xFF15803D)
        /// color/fill/success/solid/selected — A selected solid success item, such as the active segment of a segmented control.
        public static let fillSuccessSolidSelected = DSColor(light: 0xFF15803D, dark: 0xFF22C55E)
        /// color/fill/success/solid/disabled — Solid success fills of disabled controls.
        public static let fillSuccessSolidDisabled = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/success/subtle — Tinted success fill: success badges and success alert backgrounds.
        public static let fillSuccessSubtle = DSColor(light: 0xFFF0FDF4, dark: 0xFF052E16)
        /// color/fill/success/subtle/hover — The tinted success fill under the pointer, such as a tertiary button or menu row hover.
        public static let fillSuccessSubtleHover = DSColor(light: 0xFFDCFCE7, dark: 0xFF14532D)
        /// color/fill/success/subtle/pressed — The tinted success fill while pressed.
        public static let fillSuccessSubtlePressed = DSColor(light: 0xFFBBF7D0, dark: 0xFF166534)
        /// color/fill/success/subtle/selected — Selected rows and selected success items, such as a chosen segment or command.
        public static let fillSuccessSubtleSelected = DSColor(light: 0xFFDCFCE7, dark: 0xFF14532D)
        /// color/fill/success/subtle/disabled — Tinted fills of disabled controls, such as a disabled input or primary button.
        public static let fillSuccessSubtleDisabled = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/info/solid — Solid info fill: solid info badges and informational markers.
        public static let fillInfoSolid = DSColor(light: 0xFF0284C7, dark: 0xFF0284C7)
        /// color/fill/info/solid/hover — The solid info fill under the pointer.
        public static let fillInfoSolidHover = DSColor(light: 0xFF0369A1, dark: 0xFF0EA5E9)
        /// color/fill/info/solid/pressed — The solid info fill while pressed.
        public static let fillInfoSolidPressed = DSColor(light: 0xFF075985, dark: 0xFF0369A1)
        /// color/fill/info/solid/selected — A selected solid info item, such as the active segment of a segmented control.
        public static let fillInfoSolidSelected = DSColor(light: 0xFF0369A1, dark: 0xFF0EA5E9)
        /// color/fill/info/solid/disabled — Solid info fills of disabled controls.
        public static let fillInfoSolidDisabled = DSColor(light: 0xFFF1F5F9, dark: 0xFF1E293B)
        /// color/fill/info/subtle — Tinted info fill: info badges and info alert backgrounds.
        public static let fillInfoSubtle = DSColor(light: 0xFFF0F9FF, dark: 0xFF082F49)
        /// color/fill/info/subtle/hover — The tinted info fill under the pointer, such as a tertiary button or menu row hover.
        public static let fillInfoSubtleHover = DSColor(light: 0xFFE0F2FE, dark: 0xFF0C4A6E)
        /// color/fill/info/subtle/pressed — The tinted info fill while pressed.
        public static let fillInfoSubtlePressed = DSColor(light: 0xFFBAE6FD, dark: 0xFF075985)
        /// color/fill/info/subtle/selected — Selected rows and selected info items, such as a chosen segment or command.
        public static let fillInfoSubtleSelected = DSColor(light: 0xFFE0F2FE, dark: 0xFF0C4A6E)
        /// color/fill/info/subtle/disabled — Tinted fills of disabled controls, such as a disabled input or primary button.
        public static let fillInfoSubtleDisabled = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// color/fill/none — Transparent fill that keeps a layer bound, such as a ghost button at rest.
        public static let fillNone = DSColor(light: 0x00FFFFFF, dark: 0x00FFFFFF)
        /// color/fill/neutral/track — Unfilled tracks: progress bars, sliders and the off state of switches.
        public static let fillNeutralTrack = DSColor(light: 0xFFE2E8F0, dark: 0xFF1E293B)
        /// color/overlay/scrim — Scrim behind dialogs and drawers that dims the page.
        public static let overlayScrim = DSColor(light: 0x99000000, dark: 0xCC000000)
        /// color/shadow/ambient — Soft, wide shadow layer that gives every elevation its spread.
        public static let shadowAmbient = DSColor(light: 0x0D000000, dark: 0x33000000)
        /// color/shadow/key — Tighter, darker shadow layer that gives elevation its direction.
        public static let shadowKey = DSColor(light: 0x1A000000, dark: 0x66000000)
        /// color/category/slate/subtle — Background of slate category tags and badges.
        public static let categorySlateSubtle = DSColor(light: 0xFFF8FAFC, dark: 0xFF020617)
        /// color/category/slate/solid — Slate chart series, category dots and avatar fills.
        public static let categorySlateSolid = DSColor(light: 0xFF64748B, dark: 0xFF64748B)
        /// color/category/slate/text — Text and icons on the slate subtle background.
        public static let categorySlateText = DSColor(light: 0xFF334155, dark: 0xFFCBD5E1)
        /// color/category/slate/border — Outline of slate category tags and badges.
        public static let categorySlateBorder = DSColor(light: 0xFFE2E8F0, dark: 0xFF1E293B)
        /// color/category/sky/subtle — Background of sky category tags and badges.
        public static let categorySkySubtle = DSColor(light: 0xFFF0F9FF, dark: 0xFF082F49)
        /// color/category/sky/solid — Sky chart series, category dots and avatar fills.
        public static let categorySkySolid = DSColor(light: 0xFF0EA5E9, dark: 0xFF0EA5E9)
        /// color/category/sky/text — Text and icons on the sky subtle background.
        public static let categorySkyText = DSColor(light: 0xFF0369A1, dark: 0xFF7DD3FC)
        /// color/category/sky/border — Outline of sky category tags and badges.
        public static let categorySkyBorder = DSColor(light: 0xFFBAE6FD, dark: 0xFF075985)
        /// color/category/blue/subtle — Background of blue category tags and badges.
        public static let categoryBlueSubtle = DSColor(light: 0xFFF0F9FF, dark: 0xFF082F49)
        /// color/category/blue/solid — Blue chart series, category dots and avatar fills.
        public static let categoryBlueSolid = DSColor(light: 0xFF0EA5E9, dark: 0xFF0EA5E9)
        /// color/category/blue/text — Text and icons on the blue subtle background.
        public static let categoryBlueText = DSColor(light: 0xFF0369A1, dark: 0xFF7DD3FC)
        /// color/category/blue/border — Outline of blue category tags and badges.
        public static let categoryBlueBorder = DSColor(light: 0xFFBAE6FD, dark: 0xFF075985)
        /// color/category/indigo/subtle — Background of indigo category tags and badges.
        public static let categoryIndigoSubtle = DSColor(light: 0xFFEEF2FF, dark: 0xFF1E1B4B)
        /// color/category/indigo/solid — Indigo chart series, category dots and avatar fills.
        public static let categoryIndigoSolid = DSColor(light: 0xFF6366F1, dark: 0xFF6366F1)
        /// color/category/indigo/text — Text and icons on the indigo subtle background.
        public static let categoryIndigoText = DSColor(light: 0xFF4338CA, dark: 0xFFA5B4FC)
        /// color/category/indigo/border — Outline of indigo category tags and badges.
        public static let categoryIndigoBorder = DSColor(light: 0xFFC7D2FE, dark: 0xFF3730A3)
        /// color/category/purple/subtle — Background of purple category tags and badges.
        public static let categoryPurpleSubtle = DSColor(light: 0xFFFAF5FF, dark: 0xFF3B0764)
        /// color/category/purple/solid — Purple chart series, category dots and avatar fills.
        public static let categoryPurpleSolid = DSColor(light: 0xFFA855F7, dark: 0xFFA855F7)
        /// color/category/purple/text — Text and icons on the purple subtle background.
        public static let categoryPurpleText = DSColor(light: 0xFF7E22CE, dark: 0xFFD8B4FE)
        /// color/category/purple/border — Outline of purple category tags and badges.
        public static let categoryPurpleBorder = DSColor(light: 0xFFE9D5FF, dark: 0xFF6B21A8)
        /// color/category/pink/subtle — Background of pink category tags and badges.
        public static let categoryPinkSubtle = DSColor(light: 0xFFFDF2F8, dark: 0xFF500724)
        /// color/category/pink/solid — Pink chart series, category dots and avatar fills.
        public static let categoryPinkSolid = DSColor(light: 0xFFEC4899, dark: 0xFFEC4899)
        /// color/category/pink/text — Text and icons on the pink subtle background.
        public static let categoryPinkText = DSColor(light: 0xFFBE185D, dark: 0xFFF9A8D4)
        /// color/category/pink/border — Outline of pink category tags and badges.
        public static let categoryPinkBorder = DSColor(light: 0xFFFBCFE8, dark: 0xFF9D174D)
        /// color/category/orange/subtle — Background of orange category tags and badges.
        public static let categoryOrangeSubtle = DSColor(light: 0xFFFFF7ED, dark: 0xFF431407)
        /// color/category/orange/solid — Orange chart series, category dots and avatar fills.
        public static let categoryOrangeSolid = DSColor(light: 0xFFF97316, dark: 0xFFF97316)
        /// color/category/orange/text — Text and icons on the orange subtle background.
        public static let categoryOrangeText = DSColor(light: 0xFFC2410C, dark: 0xFFFDBA74)
        /// color/category/orange/border — Outline of orange category tags and badges.
        public static let categoryOrangeBorder = DSColor(light: 0xFFFED7AA, dark: 0xFF9A3412)
        /// color/category/teal/subtle — Background of teal category tags and badges.
        public static let categoryTealSubtle = DSColor(light: 0xFFF0FDFA, dark: 0xFF042F2E)
        /// color/category/teal/solid — Teal chart series, category dots and avatar fills.
        public static let categoryTealSolid = DSColor(light: 0xFF14B8A6, dark: 0xFF14B8A6)
        /// color/category/teal/text — Text and icons on the teal subtle background.
        public static let categoryTealText = DSColor(light: 0xFF0F766E, dark: 0xFF5EEAD4)
        /// color/category/teal/border — Outline of teal category tags and badges.
        public static let categoryTealBorder = DSColor(light: 0xFF99F6E4, dark: 0xFF115E59)
        /// color/text/danger/hover — Danger text under the pointer, such as a secondary danger button label.
        public static let textDangerHover = DSColor(light: 0xFF991B1B, dark: 0xFFFCA5A5)
        /// color/icon/danger/hover — Danger icons under the pointer.
        public static let iconDangerHover = DSColor(light: 0xFFB91C1C, dark: 0xFFF87171)
    }

    public enum ComponentColor {
        /// avatar/placeholder/fill — Background of initials and icon avatars.
        public static let avatarPlaceholderFill = DSColor(light: 0xFFF8FAFC, dark: 0xFF0F172A)
        /// avatar/placeholder/text — Initials on placeholder avatars.
        public static let avatarPlaceholderText = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// avatar/placeholder/icon — Icon on placeholder avatars.
        public static let avatarPlaceholderIcon = DSColor(light: 0xFF64748B, dark: 0xFF64748B)
        /// switch/track/off-hover — Track of an off switch under the pointer.
        public static let switchTrackOffHover = DSColor(light: 0xFF475569, dark: 0xFF94A3B8)
        /// switch/thumb/fill — Fill of every switch thumb.
        public static let switchThumbFill = DSColor(light: 0xFFFFFFFF, dark: 0xFF020617)
        /// social-button/google/fill — Official Google sign-in button fill; same in every mode.
        public static let socialButtonGoogleFill = DSColor(light: 0xFF1F1F1F, dark: 0xFF1F1F1F)
        /// social-button/google/fill/hover — Google sign-in button fill under the pointer.
        public static let socialButtonGoogleFillHover = DSColor(light: 0xFF303030, dark: 0xFF303030)
        /// social-button/google/fg — Label and mark colour on the Google solid button.
        public static let socialButtonGoogleFg = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// social-button/apple/fill — Official Apple sign-in button fill; same in every mode.
        public static let socialButtonAppleFill = DSColor(light: 0xFF000000, dark: 0xFF000000)
        /// social-button/apple/fill/hover — Apple sign-in button fill under the pointer.
        public static let socialButtonAppleFillHover = DSColor(light: 0xFF1C1C1E, dark: 0xFF1C1C1E)
        /// social-button/apple/fg — Label and mark colour on the Apple solid button.
        public static let socialButtonAppleFg = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// social-button/github/fill — Official GitHub sign-in button fill; same in every mode.
        public static let socialButtonGithubFill = DSColor(light: 0xFF24292F, dark: 0xFF24292F)
        /// social-button/github/fill/hover — GitHub sign-in button fill under the pointer.
        public static let socialButtonGithubFillHover = DSColor(light: 0xFF32383F, dark: 0xFF32383F)
        /// social-button/github/fg — Label and mark colour on the GitHub solid button.
        public static let socialButtonGithubFg = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// social-button/facebook/fill — Official Facebook sign-in button fill; same in every mode.
        public static let socialButtonFacebookFill = DSColor(light: 0xFF1877F2, dark: 0xFF1877F2)
        /// social-button/facebook/fill/hover — Facebook sign-in button fill under the pointer.
        public static let socialButtonFacebookFillHover = DSColor(light: 0xFF166FE5, dark: 0xFF166FE5)
        /// social-button/facebook/fg — Label and mark colour on the Facebook solid button.
        public static let socialButtonFacebookFg = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// social-button/x/fill — Official X sign-in button fill; same in every mode.
        public static let socialButtonXFill = DSColor(light: 0xFF000000, dark: 0xFF000000)
        /// social-button/x/fill/hover — X sign-in button fill under the pointer.
        public static let socialButtonXFillHover = DSColor(light: 0xFF1C1C1E, dark: 0xFF1C1C1E)
        /// social-button/x/fg — Label and mark colour on the X solid button.
        public static let socialButtonXFg = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// social-button/gitlab/fill — Official GitLab sign-in button fill; same in every mode.
        public static let socialButtonGitlabFill = DSColor(light: 0xFFFC6D26, dark: 0xFFFC6D26)
        /// social-button/gitlab/fill/hover — GitLab sign-in button fill under the pointer.
        public static let socialButtonGitlabFillHover = DSColor(light: 0xFFE2561A, dark: 0xFFE2561A)
        /// social-button/gitlab/fg — Label and mark color on the GitLab solid button: GitLab charcoal, so the label reaches 4.5:1 on GitLab orange (white is 2.85:1).
        public static let socialButtonGitlabFg = DSColor(light: 0xFF171321, dark: 0xFF171321)
        /// video-player/control/fg — Icons, timestamps and handles on video; light in every mode.
        public static let videoPlayerControlFg = DSColor(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        /// video-player/action/fill/hover — Media action under the pointer.
        public static let videoPlayerActionFillHover = DSColor(light: 0x33FFFFFF, dark: 0x33FFFFFF)
        /// video-player/overlay/fill — Overlay play button.
        public static let videoPlayerOverlayFill = DSColor(light: 0x33FFFFFF, dark: 0x33FFFFFF)
        /// video-player/overlay/fill/hover — Overlay play button under the pointer.
        public static let videoPlayerOverlayFillHover = DSColor(light: 0x4DFFFFFF, dark: 0x4DFFFFFF)
        /// video-player/track — Timeline and volume track.
        public static let videoPlayerTrack = DSColor(light: 0x4DFFFFFF, dark: 0x4DFFFFFF)
        /// video-player/track/buffer — Buffered part of the timeline.
        public static let videoPlayerTrackBuffer = DSColor(light: 0x80FFFFFF, dark: 0x80FFFFFF)
        /// video-player/tooltip/fill — Media tooltip and timestamp indicator.
        public static let videoPlayerTooltipFill = DSColor(light: 0x99000000, dark: 0xCC000000)
    }

    public enum FontWeight {
        public static let regular: CGFloat = 400
        public static let medium: CGFloat = 500
        public static let semibold: CGFloat = 600
        public static let bold: CGFloat = 700
    }

    public enum FontSize {
        public static let displayLg: CGFloat = 60
        public static let displayMd: CGFloat = 48
        public static let displaySm: CGFloat = 36
        public static let headingXl: CGFloat = 30
        public static let headingLg: CGFloat = 24
        public static let headingMd: CGFloat = 20
        public static let headingSm: CGFloat = 18
        public static let headingXs: CGFloat = 16
        public static let bodyXl: CGFloat = 20
        public static let bodyLg: CGFloat = 18
        public static let bodyMd: CGFloat = 16
        public static let bodySm: CGFloat = 14
        public static let bodyXs: CGFloat = 12
        public static let codeMd: CGFloat = 14
        public static let codeSm: CGFloat = 12
        public static let inputMin: CGFloat = 16
    }

    public enum FontLineHeight {
        public static let displayLg: CGFloat = 72
        public static let displayMd: CGFloat = 60
        public static let displaySm: CGFloat = 44
        public static let headingXl: CGFloat = 38
        public static let headingLg: CGFloat = 32
        public static let headingMd: CGFloat = 30
        public static let headingSm: CGFloat = 28
        public static let headingXs: CGFloat = 24
        public static let bodyXl: CGFloat = 30
        public static let bodyLg: CGFloat = 28
        public static let bodyMd: CGFloat = 24
        public static let bodySm: CGFloat = 20
        public static let bodyXs: CGFloat = 18
        public static let codeMd: CGFloat = 20
        public static let codeSm: CGFloat = 18
    }

    public enum FontLetterSpacing {
        public static let displayLg: CGFloat = -1.2
        public static let displayMd: CGFloat = -0.96
        public static let displaySm: CGFloat = -0.72
        public static let headingXl: CGFloat = -0.3
        public static let headingLg: CGFloat = -0.24
        public static let headingMd: CGFloat = -0.2
        public static let `default`: CGFloat = 0
    }

    public enum Space {
        public static let `none`: CGFloat = 0
        public static let xxs: CGFloat = 2
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 6
        public static let md: CGFloat = 8
        public static let lg: CGFloat = 12
        public static let xl: CGFloat = 16
        public static let space2xl: CGFloat = 20
        public static let space3xl: CGFloat = 24
        public static let space4xl: CGFloat = 32
        public static let space5xl: CGFloat = 40
        public static let space6xl: CGFloat = 48
        public static let space7xl: CGFloat = 64
        public static let space8xl: CGFloat = 80
        public static let space9xl: CGFloat = 96
        public static let space10xl: CGFloat = 128
        public static let space11xl: CGFloat = 160
        public static let optical: CGFloat = 2
    }

    public enum Size {
        public static let controlXs: CGFloat = 32
        public static let controlSm: CGFloat = 36
        public static let controlMd: CGFloat = 40
        public static let controlLg: CGFloat = 44
        public static let controlXl: CGFloat = 48
        public static let iconXs: CGFloat = 12
        public static let iconSm: CGFloat = 16
        public static let iconMd: CGFloat = 20
        public static let iconLg: CGFloat = 24
        public static let iconXl: CGFloat = 32
        public static let avatar2xs: CGFloat = 16
        public static let avatarXs: CGFloat = 24
        public static let avatarSm: CGFloat = 32
        public static let avatarMd: CGFloat = 40
        public static let avatarLg: CGFloat = 48
        public static let avatarXl: CGFloat = 56
        public static let avatar2xl: CGFloat = 64
        public static let indicatorXs: CGFloat = 6
        public static let indicatorSm: CGFloat = 8
        public static let indicatorMd: CGFloat = 10
        public static let indicatorLg: CGFloat = 12
        public static let trackSm: CGFloat = 4
        public static let trackMd: CGFloat = 6
        public static let trackLg: CGFloat = 8
        public static let widthXxs: CGFloat = 320
        public static let widthXs: CGFloat = 384
        public static let widthSm: CGFloat = 480
        public static let widthMd: CGFloat = 560
        public static let widthLg: CGFloat = 640
        public static let widthXl: CGFloat = 768
        public static let width2xl: CGFloat = 1024
        public static let width3xl: CGFloat = 1280
        public static let width4xl: CGFloat = 1440
        public static let width5xl: CGFloat = 1600
        public static let width6xl: CGFloat = 1920
        public static let containerMax: CGFloat = 1280
        public static let containerMarginMobile: CGFloat = 16
        public static let containerMarginDesktop: CGFloat = 32
        public static let measureReading: CGFloat = 640
        public static let touchMin: CGFloat = 44
    }

    public enum Radius {
        public static let `none`: CGFloat = 0
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 6
        public static let control: CGFloat = 8
        public static let indicator: CGFloat = 9999
        public static let surface: CGFloat = 12
        public static let modal: CGFloat = 16
        public static let full: CGFloat = 9999
    }

    public enum BorderWidth {
        public static let `default`: CGFloat = 1
        public static let strong: CGFloat = 2
        public static let focus: CGFloat = 2
        public static let selected: CGFloat = 2
    }

    public enum Component {
        public static let buttonPaddingXXs: CGFloat = 10
        public static let buttonPaddingXSm: CGFloat = 12
        public static let buttonPaddingXMd: CGFloat = 14
        public static let buttonPaddingXLg: CGFloat = 16
        public static let buttonPaddingXXl: CGFloat = 18
        public static let buttonGapXs: CGFloat = 4
        public static let buttonGapSm: CGFloat = 4
        public static let buttonGapMd: CGFloat = 4
        public static let buttonGapLg: CGFloat = 6
        public static let buttonGapXl: CGFloat = 6
        public static let iconButtonSizeXs: CGFloat = 28
        public static let iconButtonSizeSm: CGFloat = 32
        public static let iconButtonSizeMd: CGFloat = 36
        public static let iconButtonSizeLg: CGFloat = 44
        public static let linkGapSm: CGFloat = 4
        public static let linkGapMd: CGFloat = 4
        public static let linkGapLg: CGFloat = 6
        public static let badgePaddingXSm: CGFloat = 8
        public static let badgePaddingXMd: CGFloat = 10
        public static let badgePaddingXLg: CGFloat = 12
        public static let badgePaddingXTightSm: CGFloat = 6
        public static let badgePaddingXTightMd: CGFloat = 8
        public static let badgePaddingXTightLg: CGFloat = 10
        public static let tagHeightSm: CGFloat = 24
        public static let tagHeightMd: CGFloat = 28
        public static let tagHeightLg: CGFloat = 32
        public static let tagPaddingXMd: CGFloat = 10
        public static let tagPaddingXTightSm: CGFloat = 4
        public static let tagPaddingXTightMd: CGFloat = 4
        public static let tagPaddingXTightLg: CGFloat = 6
        public static let checkboxSizeSm: CGFloat = 16
        public static let checkboxSizeMd: CGFloat = 20
        public static let radioSizeSm: CGFloat = 16
        public static let radioSizeMd: CGFloat = 20
        public static let checkboxRadiusSm: CGFloat = 4
        public static let checkboxRadiusMd: CGFloat = 6
        public static let checkboxMarkSm: CGFloat = 12
        public static let checkboxMarkMd: CGFloat = 14
        public static let switchWidthSm: CGFloat = 36
        public static let switchWidthMd: CGFloat = 44
        public static let switchHeightSm: CGFloat = 20
        public static let switchHeightMd: CGFloat = 24
        public static let switchInset: CGFloat = 2
        public static let switchThumbSm: CGFloat = 16
        public static let switchThumbMd: CGFloat = 20
        public static let switchSlimWidthSm: CGFloat = 32
        public static let switchSlimWidthMd: CGFloat = 40
        public static let switchSlimTrackSm: CGFloat = 10
        public static let switchSlimTrackMd: CGFloat = 12
        public static let textControlPaddingXSm: CGFloat = 12
        public static let textControlPaddingXMd: CGFloat = 12
        public static let textControlPaddingXLg: CGFloat = 14
        public static let textControlMultilineMinHeight: CGFloat = 128
        public static let textControlPaddingYMultiline: CGFloat = 12
        public static let profilePhotoSizeSm: CGFloat = 72
        public static let profilePhotoSizeMd: CGFloat = 96
        public static let profilePhotoSizeLg: CGFloat = 160
        public static let profilePhotoRingSm: CGFloat = 3
        public static let profilePhotoRingMd: CGFloat = 4
        public static let profilePhotoRingLg: CGFloat = 6
        public static let progressRingThickness2xs: CGFloat = 6
        public static let progressRingThicknessXs: CGFloat = 16
        public static let progressRingThicknessSm: CGFloat = 16
        public static let progressRingThicknessMd: CGFloat = 20
        public static let progressRingThicknessLg: CGFloat = 20
        public static let spinnerThicknessSm: CGFloat = 2
        public static let spinnerThicknessMd: CGFloat = 2
        public static let spinnerThicknessLg: CGFloat = 4
        public static let spinnerThicknessXl: CGFloat = 6
        public static let spinnerSizeXl: CGFloat = 48
        public static let kbdHeightSm: CGFloat = 20
        public static let kbdHeightMd: CGFloat = 24
        public static let featuredIconSizeSm: CGFloat = 32
        public static let featuredIconSizeMd: CGFloat = 40
        public static let featuredIconSizeLg: CGFloat = 48
        public static let featuredIconSizeXl: CGFloat = 56
        public static let featuredIconIconXl: CGFloat = 28
        public static let buttonGroupItemPaddingXSm: CGFloat = 12
        public static let buttonGroupItemPaddingXMd: CGFloat = 16
        public static let buttonGroupItemPaddingYSm: CGFloat = 8
        public static let buttonGroupItemPaddingYMd: CGFloat = 8
        public static let codeFieldCellSizeSm: CGFloat = 64
        public static let codeFieldCellSizeMd: CGFloat = 80
        public static let codeFieldCellSizeLg: CGFloat = 96
        public static let avatarGroupOverlapXs: CGFloat = -4
        public static let avatarGroupOverlapSm: CGFloat = -8
        public static let avatarGroupOverlapMd: CGFloat = -12
        public static let selectListMaxHeight: CGFloat = 320
        public static let menuWidth: CGFloat = 240
        public static let badgeGroupPaddingBadgeMd: CGFloat = 4
        public static let badgeGroupPaddingMessageMd: CGFloat = 10
        public static let badgeGroupPaddingBadgeLg: CGFloat = 4
        public static let badgeGroupPaddingMessageLg: CGFloat = 10
    }

    public enum TextStyle {
        public static let displayLgSemibold = DSTextStyle(family: nil, monospaced: false, size: 60, lineHeight: 72, letterSpacing: -1.2, weight: 600)
        public static let displayLgBold = DSTextStyle(family: nil, monospaced: false, size: 60, lineHeight: 72, letterSpacing: -1.2, weight: 700)
        public static let displayMdSemibold = DSTextStyle(family: nil, monospaced: false, size: 48, lineHeight: 60, letterSpacing: -0.96, weight: 600)
        public static let displayMdBold = DSTextStyle(family: nil, monospaced: false, size: 48, lineHeight: 60, letterSpacing: -0.96, weight: 700)
        public static let displaySmSemibold = DSTextStyle(family: nil, monospaced: false, size: 36, lineHeight: 44, letterSpacing: -0.72, weight: 600)
        public static let displaySmBold = DSTextStyle(family: nil, monospaced: false, size: 36, lineHeight: 44, letterSpacing: -0.72, weight: 700)
        public static let headingXlSemibold = DSTextStyle(family: nil, monospaced: false, size: 30, lineHeight: 38, letterSpacing: -0.3, weight: 600)
        public static let headingXlBold = DSTextStyle(family: nil, monospaced: false, size: 30, lineHeight: 38, letterSpacing: -0.3, weight: 700)
        public static let headingLgSemibold = DSTextStyle(family: nil, monospaced: false, size: 24, lineHeight: 32, letterSpacing: -0.24, weight: 600)
        public static let headingLgBold = DSTextStyle(family: nil, monospaced: false, size: 24, lineHeight: 32, letterSpacing: -0.24, weight: 700)
        public static let headingMdSemibold = DSTextStyle(family: nil, monospaced: false, size: 20, lineHeight: 30, letterSpacing: -0.2, weight: 600)
        public static let headingMdBold = DSTextStyle(family: nil, monospaced: false, size: 20, lineHeight: 30, letterSpacing: -0.2, weight: 700)
        public static let headingSmSemibold = DSTextStyle(family: nil, monospaced: false, size: 18, lineHeight: 28, letterSpacing: 0, weight: 600)
        public static let headingSmBold = DSTextStyle(family: nil, monospaced: false, size: 18, lineHeight: 28, letterSpacing: 0, weight: 700)
        public static let headingXsSemibold = DSTextStyle(family: nil, monospaced: false, size: 16, lineHeight: 24, letterSpacing: 0, weight: 600)
        public static let headingXsBold = DSTextStyle(family: nil, monospaced: false, size: 16, lineHeight: 24, letterSpacing: 0, weight: 700)
        public static let bodyXlRegular = DSTextStyle(family: nil, monospaced: false, size: 20, lineHeight: 30, letterSpacing: 0, weight: 400)
        public static let bodyXlMedium = DSTextStyle(family: nil, monospaced: false, size: 20, lineHeight: 30, letterSpacing: 0, weight: 500)
        public static let bodyXlSemibold = DSTextStyle(family: nil, monospaced: false, size: 20, lineHeight: 30, letterSpacing: 0, weight: 600)
        public static let bodyLgRegular = DSTextStyle(family: nil, monospaced: false, size: 18, lineHeight: 28, letterSpacing: 0, weight: 400)
        public static let bodyLgMedium = DSTextStyle(family: nil, monospaced: false, size: 18, lineHeight: 28, letterSpacing: 0, weight: 500)
        public static let bodyLgSemibold = DSTextStyle(family: nil, monospaced: false, size: 18, lineHeight: 28, letterSpacing: 0, weight: 600)
        public static let bodyMdRegular = DSTextStyle(family: nil, monospaced: false, size: 16, lineHeight: 24, letterSpacing: 0, weight: 400)
        public static let bodyMdMedium = DSTextStyle(family: nil, monospaced: false, size: 16, lineHeight: 24, letterSpacing: 0, weight: 500)
        public static let bodyMdSemibold = DSTextStyle(family: nil, monospaced: false, size: 16, lineHeight: 24, letterSpacing: 0, weight: 600)
        public static let bodySmRegular = DSTextStyle(family: nil, monospaced: false, size: 14, lineHeight: 20, letterSpacing: 0, weight: 400)
        public static let bodySmMedium = DSTextStyle(family: nil, monospaced: false, size: 14, lineHeight: 20, letterSpacing: 0, weight: 500)
        public static let bodySmSemibold = DSTextStyle(family: nil, monospaced: false, size: 14, lineHeight: 20, letterSpacing: 0, weight: 600)
        public static let bodyXsRegular = DSTextStyle(family: nil, monospaced: false, size: 12, lineHeight: 18, letterSpacing: 0, weight: 400)
        public static let bodyXsMedium = DSTextStyle(family: nil, monospaced: false, size: 12, lineHeight: 18, letterSpacing: 0, weight: 500)
        public static let bodyXsSemibold = DSTextStyle(family: nil, monospaced: false, size: 12, lineHeight: 18, letterSpacing: 0, weight: 600)
        public static let codeMdRegular = DSTextStyle(family: nil, monospaced: true, size: 14, lineHeight: 20, letterSpacing: 0, weight: 400)
        public static let codeMdMedium = DSTextStyle(family: nil, monospaced: true, size: 14, lineHeight: 20, letterSpacing: 0, weight: 500)
        public static let codeSmRegular = DSTextStyle(family: nil, monospaced: true, size: 12, lineHeight: 18, letterSpacing: 0, weight: 400)
        public static let codeSmMedium = DSTextStyle(family: nil, monospaced: true, size: 12, lineHeight: 18, letterSpacing: 0, weight: 500)
    }

    public enum Shadow {
        public static let elevationControl: [DSShadow] = [DSShadow(x: 0, y: 1, blur: 2, spread: 0, color: DSColor(light: 0x0D000000, dark: 0x33000000))]
        public static let elevationRaised: [DSShadow] = [DSShadow(x: 0, y: 1, blur: 2, spread: 0, color: DSColor(light: 0x0D000000, dark: 0x33000000)), DSShadow(x: 0, y: 1, blur: 3, spread: 0, color: DSColor(light: 0x1A000000, dark: 0x66000000))]
        public static let elevationOverlay: [DSShadow] = [DSShadow(x: 0, y: 12, blur: 16, spread: -4, color: DSColor(light: 0x1A000000, dark: 0x66000000)), DSShadow(x: 0, y: 4, blur: 6, spread: -2, color: DSColor(light: 0x0D000000, dark: 0x33000000))]
        public static let elevationModal: [DSShadow] = [DSShadow(x: 0, y: 20, blur: 24, spread: -4, color: DSColor(light: 0x1A000000, dark: 0x66000000)), DSShadow(x: 0, y: 8, blur: 8, spread: -4, color: DSColor(light: 0x0D000000, dark: 0x33000000))]
        public static let focusDefault: [DSShadow] = [DSShadow(x: 0, y: 0, blur: 0, spread: 4, color: DSColor(light: 0xFF3B82F6, dark: 0xFF60A5FA)), DSShadow(x: 0, y: 0, blur: 0, spread: 2, color: DSColor(light: 0xFFFFFFFF, dark: 0xFF020617))]
        public static let focusDanger: [DSShadow] = [DSShadow(x: 0, y: 0, blur: 0, spread: 4, color: DSColor(light: 0xFFDC2626, dark: 0xFFF87171)), DSShadow(x: 0, y: 0, blur: 0, spread: 2, color: DSColor(light: 0xFFFFFFFF, dark: 0xFF020617))]
    }

    public enum Motion {
        public static let durationInstant = DSDuration(standard: 0, reduced: 0)
        public static let durationFast = DSDuration(standard: 120, reduced: 120)
        public static let durationBase = DSDuration(standard: 200, reduced: 0)
        public static let durationSlow = DSDuration(standard: 300, reduced: 0)
        public static let durationLoop = DSDuration(standard: 900, reduced: 1800)
        public static let easingStandard = DSEasing(0.2, 0, 0, 1)
        public static let easingEnter = DSEasing(0, 0, 0.2, 1)
        public static let easingExit = DSEasing(0.4, 0, 1, 1)
        public static let easingLinear = DSEasing(0, 0, 1, 1)
        public static let delayTooltip = DSDuration(standard: 400, reduced: 400)
        public static let delayToast = DSDuration(standard: 5000, reduced: 5000)
        public static let delayDebounce = DSDuration(standard: 250, reduced: 250)
    }
}
