// GENERATED by app/shared/scripts/build-app-tokens.mjs from figma-variables.json — do not edit.
// Fix values in the Figma variables and export again (APP.md §8).

package design.system.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Every color role. One instance per color mode; DsTheme provides the active one. */
@Immutable
data class DsColors(
    /** color/text/primary */
    val textPrimary: Color,
    /** color/text/primary/on-brand */
    val textPrimaryOnBrand: Color,
    /** color/text/secondary */
    val textSecondary: Color,
    /** color/text/secondary/hover */
    val textSecondaryHover: Color,
    /** color/text/secondary/on-brand */
    val textSecondaryOnBrand: Color,
    /** color/text/tertiary */
    val textTertiary: Color,
    /** color/text/tertiary/hover */
    val textTertiaryHover: Color,
    /** color/text/tertiary/on-brand */
    val textTertiaryOnBrand: Color,
    /** color/text/disabled */
    val textDisabled: Color,
    /** color/text/placeholder */
    val textPlaceholder: Color,
    /** color/text/inverse */
    val textInverse: Color,
    /** color/text/on-solid */
    val textOnSolid: Color,
    /** color/text/brand */
    val textBrand: Color,
    /** color/text/brand/hover */
    val textBrandHover: Color,
    /** color/text/brand/pressed */
    val textBrandPressed: Color,
    /** color/text/danger */
    val textDanger: Color,
    /** color/text/warning */
    val textWarning: Color,
    /** color/text/success */
    val textSuccess: Color,
    /** color/text/info */
    val textInfo: Color,
    /** color/icon/primary */
    val iconPrimary: Color,
    /** color/icon/primary/on-brand */
    val iconPrimaryOnBrand: Color,
    /** color/icon/secondary */
    val iconSecondary: Color,
    /** color/icon/secondary/hover */
    val iconSecondaryHover: Color,
    /** color/icon/secondary/on-brand */
    val iconSecondaryOnBrand: Color,
    /** color/icon/tertiary */
    val iconTertiary: Color,
    /** color/icon/tertiary/hover */
    val iconTertiaryHover: Color,
    /** color/icon/tertiary/on-brand */
    val iconTertiaryOnBrand: Color,
    /** color/icon/disabled */
    val iconDisabled: Color,
    /** color/icon/placeholder */
    val iconPlaceholder: Color,
    /** color/icon/inverse */
    val iconInverse: Color,
    /** color/icon/on-solid */
    val iconOnSolid: Color,
    /** color/icon/brand */
    val iconBrand: Color,
    /** color/icon/brand/hover */
    val iconBrandHover: Color,
    /** color/icon/brand/pressed */
    val iconBrandPressed: Color,
    /** color/icon/danger */
    val iconDanger: Color,
    /** color/icon/warning */
    val iconWarning: Color,
    /** color/icon/success */
    val iconSuccess: Color,
    /** color/icon/info */
    val iconInfo: Color,
    /** color/border/subtle */
    val borderSubtle: Color,
    /** color/border/default */
    val borderDefault: Color,
    /** color/border/strong */
    val borderStrong: Color,
    /** color/border/brand */
    val borderBrand: Color,
    /** color/border/brand/subtle */
    val borderBrandSubtle: Color,
    /** color/border/danger */
    val borderDanger: Color,
    /** color/border/danger/subtle */
    val borderDangerSubtle: Color,
    /** color/border/warning */
    val borderWarning: Color,
    /** color/border/warning/subtle */
    val borderWarningSubtle: Color,
    /** color/border/success */
    val borderSuccess: Color,
    /** color/border/success/subtle */
    val borderSuccessSubtle: Color,
    /** color/border/info */
    val borderInfo: Color,
    /** color/border/info/subtle */
    val borderInfoSubtle: Color,
    /** color/border/focus */
    val borderFocus: Color,
    /** color/border/disabled */
    val borderDisabled: Color,
    /** color/surface/base */
    val surfaceBase: Color,
    /** color/surface/base/hover */
    val surfaceBaseHover: Color,
    /** color/surface/base/pressed */
    val surfaceBasePressed: Color,
    /** color/surface/sunken */
    val surfaceSunken: Color,
    /** color/surface/sunken/hover */
    val surfaceSunkenHover: Color,
    /** color/surface/raised */
    val surfaceRaised: Color,
    /** color/surface/raised/hover */
    val surfaceRaisedHover: Color,
    /** color/surface/overlay */
    val surfaceOverlay: Color,
    /** color/surface/inverse */
    val surfaceInverse: Color,
    /** color/surface/brand-subtle */
    val surfaceBrandSubtle: Color,
    /** color/surface/brand-subtle/hover */
    val surfaceBrandSubtleHover: Color,
    /** color/surface/brand-solid */
    val surfaceBrandSolid: Color,
    /** color/fill/neutral/solid */
    val fillNeutralSolid: Color,
    /** color/fill/neutral/solid/hover */
    val fillNeutralSolidHover: Color,
    /** color/fill/neutral/solid/pressed */
    val fillNeutralSolidPressed: Color,
    /** color/fill/neutral/solid/selected */
    val fillNeutralSolidSelected: Color,
    /** color/fill/neutral/solid/disabled */
    val fillNeutralSolidDisabled: Color,
    /** color/fill/neutral/subtle */
    val fillNeutralSubtle: Color,
    /** color/fill/neutral/subtle/hover */
    val fillNeutralSubtleHover: Color,
    /** color/fill/neutral/subtle/pressed */
    val fillNeutralSubtlePressed: Color,
    /** color/fill/neutral/subtle/selected */
    val fillNeutralSubtleSelected: Color,
    /** color/fill/neutral/subtle/disabled */
    val fillNeutralSubtleDisabled: Color,
    /** color/fill/brand/solid */
    val fillBrandSolid: Color,
    /** color/fill/brand/solid/hover */
    val fillBrandSolidHover: Color,
    /** color/fill/brand/solid/pressed */
    val fillBrandSolidPressed: Color,
    /** color/fill/brand/solid/selected */
    val fillBrandSolidSelected: Color,
    /** color/fill/brand/solid/disabled */
    val fillBrandSolidDisabled: Color,
    /** color/fill/brand/subtle */
    val fillBrandSubtle: Color,
    /** color/fill/brand/subtle/hover */
    val fillBrandSubtleHover: Color,
    /** color/fill/brand/subtle/pressed */
    val fillBrandSubtlePressed: Color,
    /** color/fill/brand/subtle/selected */
    val fillBrandSubtleSelected: Color,
    /** color/fill/brand/subtle/disabled */
    val fillBrandSubtleDisabled: Color,
    /** color/fill/danger/solid */
    val fillDangerSolid: Color,
    /** color/fill/danger/solid/hover */
    val fillDangerSolidHover: Color,
    /** color/fill/danger/solid/pressed */
    val fillDangerSolidPressed: Color,
    /** color/fill/danger/solid/selected */
    val fillDangerSolidSelected: Color,
    /** color/fill/danger/solid/disabled */
    val fillDangerSolidDisabled: Color,
    /** color/fill/danger/subtle */
    val fillDangerSubtle: Color,
    /** color/fill/danger/subtle/hover */
    val fillDangerSubtleHover: Color,
    /** color/fill/danger/subtle/pressed */
    val fillDangerSubtlePressed: Color,
    /** color/fill/danger/subtle/selected */
    val fillDangerSubtleSelected: Color,
    /** color/fill/danger/subtle/disabled */
    val fillDangerSubtleDisabled: Color,
    /** color/fill/warning/solid */
    val fillWarningSolid: Color,
    /** color/fill/warning/solid/hover */
    val fillWarningSolidHover: Color,
    /** color/fill/warning/solid/pressed */
    val fillWarningSolidPressed: Color,
    /** color/fill/warning/solid/selected */
    val fillWarningSolidSelected: Color,
    /** color/fill/warning/solid/disabled */
    val fillWarningSolidDisabled: Color,
    /** color/fill/warning/subtle */
    val fillWarningSubtle: Color,
    /** color/fill/warning/subtle/hover */
    val fillWarningSubtleHover: Color,
    /** color/fill/warning/subtle/pressed */
    val fillWarningSubtlePressed: Color,
    /** color/fill/warning/subtle/selected */
    val fillWarningSubtleSelected: Color,
    /** color/fill/warning/subtle/disabled */
    val fillWarningSubtleDisabled: Color,
    /** color/fill/success/solid */
    val fillSuccessSolid: Color,
    /** color/fill/success/solid/hover */
    val fillSuccessSolidHover: Color,
    /** color/fill/success/solid/pressed */
    val fillSuccessSolidPressed: Color,
    /** color/fill/success/solid/selected */
    val fillSuccessSolidSelected: Color,
    /** color/fill/success/solid/disabled */
    val fillSuccessSolidDisabled: Color,
    /** color/fill/success/subtle */
    val fillSuccessSubtle: Color,
    /** color/fill/success/subtle/hover */
    val fillSuccessSubtleHover: Color,
    /** color/fill/success/subtle/pressed */
    val fillSuccessSubtlePressed: Color,
    /** color/fill/success/subtle/selected */
    val fillSuccessSubtleSelected: Color,
    /** color/fill/success/subtle/disabled */
    val fillSuccessSubtleDisabled: Color,
    /** color/fill/info/solid */
    val fillInfoSolid: Color,
    /** color/fill/info/solid/hover */
    val fillInfoSolidHover: Color,
    /** color/fill/info/solid/pressed */
    val fillInfoSolidPressed: Color,
    /** color/fill/info/solid/selected */
    val fillInfoSolidSelected: Color,
    /** color/fill/info/solid/disabled */
    val fillInfoSolidDisabled: Color,
    /** color/fill/info/subtle */
    val fillInfoSubtle: Color,
    /** color/fill/info/subtle/hover */
    val fillInfoSubtleHover: Color,
    /** color/fill/info/subtle/pressed */
    val fillInfoSubtlePressed: Color,
    /** color/fill/info/subtle/selected */
    val fillInfoSubtleSelected: Color,
    /** color/fill/info/subtle/disabled */
    val fillInfoSubtleDisabled: Color,
    /** color/fill/none */
    val fillNone: Color,
    /** color/fill/neutral/track */
    val fillNeutralTrack: Color,
    /** color/overlay/scrim */
    val overlayScrim: Color,
    /** color/shadow/ambient */
    val shadowAmbient: Color,
    /** color/shadow/key */
    val shadowKey: Color,
    /** color/category/slate/subtle */
    val categorySlateSubtle: Color,
    /** color/category/slate/solid */
    val categorySlateSolid: Color,
    /** color/category/slate/text */
    val categorySlateText: Color,
    /** color/category/slate/border */
    val categorySlateBorder: Color,
    /** color/category/sky/subtle */
    val categorySkySubtle: Color,
    /** color/category/sky/solid */
    val categorySkySolid: Color,
    /** color/category/sky/text */
    val categorySkyText: Color,
    /** color/category/sky/border */
    val categorySkyBorder: Color,
    /** color/category/blue/subtle */
    val categoryBlueSubtle: Color,
    /** color/category/blue/solid */
    val categoryBlueSolid: Color,
    /** color/category/blue/text */
    val categoryBlueText: Color,
    /** color/category/blue/border */
    val categoryBlueBorder: Color,
    /** color/category/indigo/subtle */
    val categoryIndigoSubtle: Color,
    /** color/category/indigo/solid */
    val categoryIndigoSolid: Color,
    /** color/category/indigo/text */
    val categoryIndigoText: Color,
    /** color/category/indigo/border */
    val categoryIndigoBorder: Color,
    /** color/category/purple/subtle */
    val categoryPurpleSubtle: Color,
    /** color/category/purple/solid */
    val categoryPurpleSolid: Color,
    /** color/category/purple/text */
    val categoryPurpleText: Color,
    /** color/category/purple/border */
    val categoryPurpleBorder: Color,
    /** color/category/pink/subtle */
    val categoryPinkSubtle: Color,
    /** color/category/pink/solid */
    val categoryPinkSolid: Color,
    /** color/category/pink/text */
    val categoryPinkText: Color,
    /** color/category/pink/border */
    val categoryPinkBorder: Color,
    /** color/category/orange/subtle */
    val categoryOrangeSubtle: Color,
    /** color/category/orange/solid */
    val categoryOrangeSolid: Color,
    /** color/category/orange/text */
    val categoryOrangeText: Color,
    /** color/category/orange/border */
    val categoryOrangeBorder: Color,
    /** color/category/teal/subtle */
    val categoryTealSubtle: Color,
    /** color/category/teal/solid */
    val categoryTealSolid: Color,
    /** color/category/teal/text */
    val categoryTealText: Color,
    /** color/category/teal/border */
    val categoryTealBorder: Color,
    /** color/text/danger/hover */
    val textDangerHover: Color,
    /** color/icon/danger/hover */
    val iconDangerHover: Color,
    /** avatar/placeholder/fill */
    val avatarPlaceholderFill: Color,
    /** avatar/placeholder/text */
    val avatarPlaceholderText: Color,
    /** avatar/placeholder/icon */
    val avatarPlaceholderIcon: Color,
    /** switch/track/off-hover */
    val switchTrackOffHover: Color,
    /** switch/thumb/fill */
    val switchThumbFill: Color,
    /** social-button/google/fill */
    val socialButtonGoogleFill: Color,
    /** social-button/google/fill/hover */
    val socialButtonGoogleFillHover: Color,
    /** social-button/google/fg */
    val socialButtonGoogleFg: Color,
    /** social-button/apple/fill */
    val socialButtonAppleFill: Color,
    /** social-button/apple/fill/hover */
    val socialButtonAppleFillHover: Color,
    /** social-button/apple/fg */
    val socialButtonAppleFg: Color,
    /** social-button/github/fill */
    val socialButtonGithubFill: Color,
    /** social-button/github/fill/hover */
    val socialButtonGithubFillHover: Color,
    /** social-button/github/fg */
    val socialButtonGithubFg: Color,
    /** social-button/facebook/fill */
    val socialButtonFacebookFill: Color,
    /** social-button/facebook/fill/hover */
    val socialButtonFacebookFillHover: Color,
    /** social-button/facebook/fg */
    val socialButtonFacebookFg: Color,
    /** social-button/x/fill */
    val socialButtonXFill: Color,
    /** social-button/x/fill/hover */
    val socialButtonXFillHover: Color,
    /** social-button/x/fg */
    val socialButtonXFg: Color,
    /** social-button/gitlab/fill */
    val socialButtonGitlabFill: Color,
    /** social-button/gitlab/fill/hover */
    val socialButtonGitlabFillHover: Color,
    /** social-button/gitlab/fg */
    val socialButtonGitlabFg: Color,
    /** video-player/control/fg */
    val videoPlayerControlFg: Color,
    /** video-player/action/fill/hover */
    val videoPlayerActionFillHover: Color,
    /** video-player/overlay/fill */
    val videoPlayerOverlayFill: Color,
    /** video-player/overlay/fill/hover */
    val videoPlayerOverlayFillHover: Color,
    /** video-player/track */
    val videoPlayerTrack: Color,
    /** video-player/track/buffer */
    val videoPlayerTrackBuffer: Color,
    /** video-player/tooltip/fill */
    val videoPlayerTooltipFill: Color,
)

val LightDsColors = DsColors(
    textPrimary = Color(0xFF0F172A),
    textPrimaryOnBrand = Color(0xFFFFFFFF),
    textSecondary = Color(0xFF334155),
    textSecondaryHover = Color(0xFF1E293B),
    textSecondaryOnBrand = Color(0xFFDBEAFE),
    textTertiary = Color(0xFF475569),
    textTertiaryHover = Color(0xFF334155),
    textTertiaryOnBrand = Color(0xFFBFDBFE),
    textDisabled = Color(0xFF94A3B8),
    textPlaceholder = Color(0xFF475569),
    textInverse = Color(0xFFFFFFFF),
    textOnSolid = Color(0xFFFFFFFF),
    textBrand = Color(0xFF1D4ED8),
    textBrandHover = Color(0xFF1E40AF),
    textBrandPressed = Color(0xFF1E3A8A),
    textDanger = Color(0xFF991B1B),
    textWarning = Color(0xFFB45309),
    textSuccess = Color(0xFF15803D),
    textInfo = Color(0xFF0369A1),
    iconPrimary = Color(0xFF1E293B),
    iconPrimaryOnBrand = Color(0xFFFFFFFF),
    iconSecondary = Color(0xFF475569),
    iconSecondaryHover = Color(0xFF334155),
    iconSecondaryOnBrand = Color(0xFFBFDBFE),
    iconTertiary = Color(0xFF64748B),
    iconTertiaryHover = Color(0xFF475569),
    iconTertiaryOnBrand = Color(0xFF93C5FD),
    iconDisabled = Color(0xFFCBD5E1),
    iconPlaceholder = Color(0xFF94A3B8),
    iconInverse = Color(0xFFFFFFFF),
    iconOnSolid = Color(0xFFFFFFFF),
    iconBrand = Color(0xFF2563EB),
    iconBrandHover = Color(0xFF1D4ED8),
    iconBrandPressed = Color(0xFF1E40AF),
    iconDanger = Color(0xFFDC2626),
    iconWarning = Color(0xFFD97706),
    iconSuccess = Color(0xFF16A34A),
    iconInfo = Color(0xFF0284C7),
    borderSubtle = Color(0xFFE2E8F0),
    borderDefault = Color(0xFFCBD5E1),
    borderStrong = Color(0xFF475569),
    borderBrand = Color(0xFF2563EB),
    borderBrandSubtle = Color(0xFF93C5FD),
    borderDanger = Color(0xFFDC2626),
    borderDangerSubtle = Color(0xFFFCA5A5),
    borderWarning = Color(0xFFF59E0B),
    borderWarningSubtle = Color(0xFFFCD34D),
    borderSuccess = Color(0xFF16A34A),
    borderSuccessSubtle = Color(0xFF86EFAC),
    borderInfo = Color(0xFF0284C7),
    borderInfoSubtle = Color(0xFF7DD3FC),
    borderFocus = Color(0xFF3B82F6),
    borderDisabled = Color(0xFFE2E8F0),
    surfaceBase = Color(0xFFFFFFFF),
    surfaceBaseHover = Color(0xFFF8FAFC),
    surfaceBasePressed = Color(0xFFF1F5F9),
    surfaceSunken = Color(0xFFF8FAFC),
    surfaceSunkenHover = Color(0xFFF1F5F9),
    surfaceRaised = Color(0xFFFFFFFF),
    surfaceRaisedHover = Color(0xFFF8FAFC),
    surfaceOverlay = Color(0xFFFFFFFF),
    surfaceInverse = Color(0xFF0F172A),
    surfaceBrandSubtle = Color(0xFFEFF6FF),
    surfaceBrandSubtleHover = Color(0xFFDBEAFE),
    surfaceBrandSolid = Color(0xFF1D4ED8),
    fillNeutralSolid = Color(0xFF0F172A),
    fillNeutralSolidHover = Color(0xFF1E293B),
    fillNeutralSolidPressed = Color(0xFF334155),
    fillNeutralSolidSelected = Color(0xFF1E293B),
    fillNeutralSolidDisabled = Color(0xFFF1F5F9),
    fillNeutralSubtle = Color(0xFFF8FAFC),
    fillNeutralSubtleHover = Color(0xFFF1F5F9),
    fillNeutralSubtlePressed = Color(0xFFE2E8F0),
    fillNeutralSubtleSelected = Color(0xFFF1F5F9),
    fillNeutralSubtleDisabled = Color(0xFFF8FAFC),
    fillBrandSolid = Color(0xFF2563EB),
    fillBrandSolidHover = Color(0xFF1D4ED8),
    fillBrandSolidPressed = Color(0xFF1E40AF),
    fillBrandSolidSelected = Color(0xFF1D4ED8),
    fillBrandSolidDisabled = Color(0xFFF1F5F9),
    fillBrandSubtle = Color(0xFFEFF6FF),
    fillBrandSubtleHover = Color(0xFFDBEAFE),
    fillBrandSubtlePressed = Color(0xFFBFDBFE),
    fillBrandSubtleSelected = Color(0xFFDBEAFE),
    fillBrandSubtleDisabled = Color(0xFFF8FAFC),
    fillDangerSolid = Color(0xFFDC2626),
    fillDangerSolidHover = Color(0xFFB91C1C),
    fillDangerSolidPressed = Color(0xFF991B1B),
    fillDangerSolidSelected = Color(0xFFB91C1C),
    fillDangerSolidDisabled = Color(0xFFF1F5F9),
    fillDangerSubtle = Color(0xFFFEF2F2),
    fillDangerSubtleHover = Color(0xFFFEE2E2),
    fillDangerSubtlePressed = Color(0xFFFECACA),
    fillDangerSubtleSelected = Color(0xFFFEE2E2),
    fillDangerSubtleDisabled = Color(0xFFF8FAFC),
    fillWarningSolid = Color(0xFFD97706),
    fillWarningSolidHover = Color(0xFFB45309),
    fillWarningSolidPressed = Color(0xFF92400E),
    fillWarningSolidSelected = Color(0xFFB45309),
    fillWarningSolidDisabled = Color(0xFFF1F5F9),
    fillWarningSubtle = Color(0xFFFFFBEB),
    fillWarningSubtleHover = Color(0xFFFEF3C7),
    fillWarningSubtlePressed = Color(0xFFFDE68A),
    fillWarningSubtleSelected = Color(0xFFFEF3C7),
    fillWarningSubtleDisabled = Color(0xFFF8FAFC),
    fillSuccessSolid = Color(0xFF16A34A),
    fillSuccessSolidHover = Color(0xFF15803D),
    fillSuccessSolidPressed = Color(0xFF166534),
    fillSuccessSolidSelected = Color(0xFF15803D),
    fillSuccessSolidDisabled = Color(0xFFF1F5F9),
    fillSuccessSubtle = Color(0xFFF0FDF4),
    fillSuccessSubtleHover = Color(0xFFDCFCE7),
    fillSuccessSubtlePressed = Color(0xFFBBF7D0),
    fillSuccessSubtleSelected = Color(0xFFDCFCE7),
    fillSuccessSubtleDisabled = Color(0xFFF8FAFC),
    fillInfoSolid = Color(0xFF0284C7),
    fillInfoSolidHover = Color(0xFF0369A1),
    fillInfoSolidPressed = Color(0xFF075985),
    fillInfoSolidSelected = Color(0xFF0369A1),
    fillInfoSolidDisabled = Color(0xFFF1F5F9),
    fillInfoSubtle = Color(0xFFF0F9FF),
    fillInfoSubtleHover = Color(0xFFE0F2FE),
    fillInfoSubtlePressed = Color(0xFFBAE6FD),
    fillInfoSubtleSelected = Color(0xFFE0F2FE),
    fillInfoSubtleDisabled = Color(0xFFF8FAFC),
    fillNone = Color(0x00FFFFFF),
    fillNeutralTrack = Color(0xFFE2E8F0),
    overlayScrim = Color(0x99000000),
    shadowAmbient = Color(0x0D000000),
    shadowKey = Color(0x1A000000),
    categorySlateSubtle = Color(0xFFF8FAFC),
    categorySlateSolid = Color(0xFF64748B),
    categorySlateText = Color(0xFF334155),
    categorySlateBorder = Color(0xFFE2E8F0),
    categorySkySubtle = Color(0xFFF0F9FF),
    categorySkySolid = Color(0xFF0EA5E9),
    categorySkyText = Color(0xFF0369A1),
    categorySkyBorder = Color(0xFFBAE6FD),
    categoryBlueSubtle = Color(0xFFF0F9FF),
    categoryBlueSolid = Color(0xFF0EA5E9),
    categoryBlueText = Color(0xFF0369A1),
    categoryBlueBorder = Color(0xFFBAE6FD),
    categoryIndigoSubtle = Color(0xFFEEF2FF),
    categoryIndigoSolid = Color(0xFF6366F1),
    categoryIndigoText = Color(0xFF4338CA),
    categoryIndigoBorder = Color(0xFFC7D2FE),
    categoryPurpleSubtle = Color(0xFFFAF5FF),
    categoryPurpleSolid = Color(0xFFA855F7),
    categoryPurpleText = Color(0xFF7E22CE),
    categoryPurpleBorder = Color(0xFFE9D5FF),
    categoryPinkSubtle = Color(0xFFFDF2F8),
    categoryPinkSolid = Color(0xFFEC4899),
    categoryPinkText = Color(0xFFBE185D),
    categoryPinkBorder = Color(0xFFFBCFE8),
    categoryOrangeSubtle = Color(0xFFFFF7ED),
    categoryOrangeSolid = Color(0xFFF97316),
    categoryOrangeText = Color(0xFFC2410C),
    categoryOrangeBorder = Color(0xFFFED7AA),
    categoryTealSubtle = Color(0xFFF0FDFA),
    categoryTealSolid = Color(0xFF14B8A6),
    categoryTealText = Color(0xFF0F766E),
    categoryTealBorder = Color(0xFF99F6E4),
    textDangerHover = Color(0xFF991B1B),
    iconDangerHover = Color(0xFFB91C1C),
    avatarPlaceholderFill = Color(0xFFF8FAFC),
    avatarPlaceholderText = Color(0xFF475569),
    avatarPlaceholderIcon = Color(0xFF64748B),
    switchTrackOffHover = Color(0xFF475569),
    switchThumbFill = Color(0xFFFFFFFF),
    socialButtonGoogleFill = Color(0xFF1F1F1F),
    socialButtonGoogleFillHover = Color(0xFF303030),
    socialButtonGoogleFg = Color(0xFFFFFFFF),
    socialButtonAppleFill = Color(0xFF000000),
    socialButtonAppleFillHover = Color(0xFF1C1C1E),
    socialButtonAppleFg = Color(0xFFFFFFFF),
    socialButtonGithubFill = Color(0xFF24292F),
    socialButtonGithubFillHover = Color(0xFF32383F),
    socialButtonGithubFg = Color(0xFFFFFFFF),
    socialButtonFacebookFill = Color(0xFF1877F2),
    socialButtonFacebookFillHover = Color(0xFF166FE5),
    socialButtonFacebookFg = Color(0xFFFFFFFF),
    socialButtonXFill = Color(0xFF000000),
    socialButtonXFillHover = Color(0xFF1C1C1E),
    socialButtonXFg = Color(0xFFFFFFFF),
    socialButtonGitlabFill = Color(0xFFFC6D26),
    socialButtonGitlabFillHover = Color(0xFFE2561A),
    socialButtonGitlabFg = Color(0xFF171321),
    videoPlayerControlFg = Color(0xFFFFFFFF),
    videoPlayerActionFillHover = Color(0x33FFFFFF),
    videoPlayerOverlayFill = Color(0x33FFFFFF),
    videoPlayerOverlayFillHover = Color(0x4DFFFFFF),
    videoPlayerTrack = Color(0x4DFFFFFF),
    videoPlayerTrackBuffer = Color(0x80FFFFFF),
    videoPlayerTooltipFill = Color(0x99000000),
)

val DarkDsColors = DsColors(
    textPrimary = Color(0xFFF8FAFC),
    textPrimaryOnBrand = Color(0xFFFFFFFF),
    textSecondary = Color(0xFFCBD5E1),
    textSecondaryHover = Color(0xFFE2E8F0),
    textSecondaryOnBrand = Color(0xFFDBEAFE),
    textTertiary = Color(0xFF94A3B8),
    textTertiaryHover = Color(0xFFCBD5E1),
    textTertiaryOnBrand = Color(0xFFBFDBFE),
    textDisabled = Color(0xFF475569),
    textPlaceholder = Color(0xFF94A3B8),
    textInverse = Color(0xFF0F172A),
    textOnSolid = Color(0xFFFFFFFF),
    textBrand = Color(0xFF93C5FD),
    textBrandHover = Color(0xFFBFDBFE),
    textBrandPressed = Color(0xFFDBEAFE),
    textDanger = Color(0xFFFECACA),
    textWarning = Color(0xFFFCD34D),
    textSuccess = Color(0xFF86EFAC),
    textInfo = Color(0xFF7DD3FC),
    iconPrimary = Color(0xFFF1F5F9),
    iconPrimaryOnBrand = Color(0xFFFFFFFF),
    iconSecondary = Color(0xFF94A3B8),
    iconSecondaryHover = Color(0xFFCBD5E1),
    iconSecondaryOnBrand = Color(0xFFBFDBFE),
    iconTertiary = Color(0xFF64748B),
    iconTertiaryHover = Color(0xFF94A3B8),
    iconTertiaryOnBrand = Color(0xFF93C5FD),
    iconDisabled = Color(0xFF334155),
    iconPlaceholder = Color(0xFF475569),
    iconInverse = Color(0xFF0F172A),
    iconOnSolid = Color(0xFFFFFFFF),
    iconBrand = Color(0xFF60A5FA),
    iconBrandHover = Color(0xFF93C5FD),
    iconBrandPressed = Color(0xFFBFDBFE),
    iconDanger = Color(0xFFEF4444),
    iconWarning = Color(0xFFF59E0B),
    iconSuccess = Color(0xFF22C55E),
    iconInfo = Color(0xFF0EA5E9),
    borderSubtle = Color(0xFF1E293B),
    borderDefault = Color(0xFF334155),
    borderStrong = Color(0xFF94A3B8),
    borderBrand = Color(0xFF60A5FA),
    borderBrandSubtle = Color(0xFF1E40AF),
    borderDanger = Color(0xFFF87171),
    borderDangerSubtle = Color(0xFF991B1B),
    borderWarning = Color(0xFFFBBF24),
    borderWarningSubtle = Color(0xFF92400E),
    borderSuccess = Color(0xFF4ADE80),
    borderSuccessSubtle = Color(0xFF166534),
    borderInfo = Color(0xFF38BDF8),
    borderInfoSubtle = Color(0xFF075985),
    borderFocus = Color(0xFF60A5FA),
    borderDisabled = Color(0xFF1E293B),
    surfaceBase = Color(0xFF020617),
    surfaceBaseHover = Color(0xFF0F172A),
    surfaceBasePressed = Color(0xFF1E293B),
    surfaceSunken = Color(0xFF000000),
    surfaceSunkenHover = Color(0xFF0F172A),
    surfaceRaised = Color(0xFF0F172A),
    surfaceRaisedHover = Color(0xFF1E293B),
    surfaceOverlay = Color(0xFF1E293B),
    surfaceInverse = Color(0xFFF8FAFC),
    surfaceBrandSubtle = Color(0xFF172554),
    surfaceBrandSubtleHover = Color(0xFF1E3A8A),
    surfaceBrandSolid = Color(0xFF1D4ED8),
    fillNeutralSolid = Color(0xFFF8FAFC),
    fillNeutralSolidHover = Color(0xFFF1F5F9),
    fillNeutralSolidPressed = Color(0xFFE2E8F0),
    fillNeutralSolidSelected = Color(0xFFF1F5F9),
    fillNeutralSolidDisabled = Color(0xFF1E293B),
    fillNeutralSubtle = Color(0xFF0F172A),
    fillNeutralSubtleHover = Color(0xFF1E293B),
    fillNeutralSubtlePressed = Color(0xFF334155),
    fillNeutralSubtleSelected = Color(0xFF1E293B),
    fillNeutralSubtleDisabled = Color(0xFF0F172A),
    fillBrandSolid = Color(0xFF2563EB),
    fillBrandSolidHover = Color(0xFF1D4ED8),
    fillBrandSolidPressed = Color(0xFF1E40AF),
    fillBrandSolidSelected = Color(0xFF1D4ED8),
    fillBrandSolidDisabled = Color(0xFF1E293B),
    fillBrandSubtle = Color(0xFF172554),
    fillBrandSubtleHover = Color(0xFF1E3A8A),
    fillBrandSubtlePressed = Color(0xFF1E40AF),
    fillBrandSubtleSelected = Color(0xFF1E3A8A),
    fillBrandSubtleDisabled = Color(0xFF0F172A),
    fillDangerSolid = Color(0xFFDC2626),
    fillDangerSolidHover = Color(0xFFB91C1C),
    fillDangerSolidPressed = Color(0xFF991B1B),
    fillDangerSolidSelected = Color(0xFFB91C1C),
    fillDangerSolidDisabled = Color(0xFF1E293B),
    fillDangerSubtle = Color(0xFF450A0A),
    fillDangerSubtleHover = Color(0xFF7F1D1D),
    fillDangerSubtlePressed = Color(0xFF991B1B),
    fillDangerSubtleSelected = Color(0xFF7F1D1D),
    fillDangerSubtleDisabled = Color(0xFF0F172A),
    fillWarningSolid = Color(0xFFD97706),
    fillWarningSolidHover = Color(0xFFF59E0B),
    fillWarningSolidPressed = Color(0xFFB45309),
    fillWarningSolidSelected = Color(0xFFF59E0B),
    fillWarningSolidDisabled = Color(0xFF1E293B),
    fillWarningSubtle = Color(0xFF451A03),
    fillWarningSubtleHover = Color(0xFF78350F),
    fillWarningSubtlePressed = Color(0xFF92400E),
    fillWarningSubtleSelected = Color(0xFF78350F),
    fillWarningSubtleDisabled = Color(0xFF0F172A),
    fillSuccessSolid = Color(0xFF16A34A),
    fillSuccessSolidHover = Color(0xFF22C55E),
    fillSuccessSolidPressed = Color(0xFF15803D),
    fillSuccessSolidSelected = Color(0xFF22C55E),
    fillSuccessSolidDisabled = Color(0xFF1E293B),
    fillSuccessSubtle = Color(0xFF052E16),
    fillSuccessSubtleHover = Color(0xFF14532D),
    fillSuccessSubtlePressed = Color(0xFF166534),
    fillSuccessSubtleSelected = Color(0xFF14532D),
    fillSuccessSubtleDisabled = Color(0xFF0F172A),
    fillInfoSolid = Color(0xFF0284C7),
    fillInfoSolidHover = Color(0xFF0EA5E9),
    fillInfoSolidPressed = Color(0xFF0369A1),
    fillInfoSolidSelected = Color(0xFF0EA5E9),
    fillInfoSolidDisabled = Color(0xFF1E293B),
    fillInfoSubtle = Color(0xFF082F49),
    fillInfoSubtleHover = Color(0xFF0C4A6E),
    fillInfoSubtlePressed = Color(0xFF075985),
    fillInfoSubtleSelected = Color(0xFF0C4A6E),
    fillInfoSubtleDisabled = Color(0xFF0F172A),
    fillNone = Color(0x00FFFFFF),
    fillNeutralTrack = Color(0xFF1E293B),
    overlayScrim = Color(0xCC000000),
    shadowAmbient = Color(0x33000000),
    shadowKey = Color(0x66000000),
    categorySlateSubtle = Color(0xFF020617),
    categorySlateSolid = Color(0xFF64748B),
    categorySlateText = Color(0xFFCBD5E1),
    categorySlateBorder = Color(0xFF1E293B),
    categorySkySubtle = Color(0xFF082F49),
    categorySkySolid = Color(0xFF0EA5E9),
    categorySkyText = Color(0xFF7DD3FC),
    categorySkyBorder = Color(0xFF075985),
    categoryBlueSubtle = Color(0xFF082F49),
    categoryBlueSolid = Color(0xFF0EA5E9),
    categoryBlueText = Color(0xFF7DD3FC),
    categoryBlueBorder = Color(0xFF075985),
    categoryIndigoSubtle = Color(0xFF1E1B4B),
    categoryIndigoSolid = Color(0xFF6366F1),
    categoryIndigoText = Color(0xFFA5B4FC),
    categoryIndigoBorder = Color(0xFF3730A3),
    categoryPurpleSubtle = Color(0xFF3B0764),
    categoryPurpleSolid = Color(0xFFA855F7),
    categoryPurpleText = Color(0xFFD8B4FE),
    categoryPurpleBorder = Color(0xFF6B21A8),
    categoryPinkSubtle = Color(0xFF500724),
    categoryPinkSolid = Color(0xFFEC4899),
    categoryPinkText = Color(0xFFF9A8D4),
    categoryPinkBorder = Color(0xFF9D174D),
    categoryOrangeSubtle = Color(0xFF431407),
    categoryOrangeSolid = Color(0xFFF97316),
    categoryOrangeText = Color(0xFFFDBA74),
    categoryOrangeBorder = Color(0xFF9A3412),
    categoryTealSubtle = Color(0xFF042F2E),
    categoryTealSolid = Color(0xFF14B8A6),
    categoryTealText = Color(0xFF5EEAD4),
    categoryTealBorder = Color(0xFF115E59),
    textDangerHover = Color(0xFFFCA5A5),
    iconDangerHover = Color(0xFFF87171),
    avatarPlaceholderFill = Color(0xFF0F172A),
    avatarPlaceholderText = Color(0xFF94A3B8),
    avatarPlaceholderIcon = Color(0xFF64748B),
    switchTrackOffHover = Color(0xFF94A3B8),
    switchThumbFill = Color(0xFF020617),
    socialButtonGoogleFill = Color(0xFF1F1F1F),
    socialButtonGoogleFillHover = Color(0xFF303030),
    socialButtonGoogleFg = Color(0xFFFFFFFF),
    socialButtonAppleFill = Color(0xFF000000),
    socialButtonAppleFillHover = Color(0xFF1C1C1E),
    socialButtonAppleFg = Color(0xFFFFFFFF),
    socialButtonGithubFill = Color(0xFF24292F),
    socialButtonGithubFillHover = Color(0xFF32383F),
    socialButtonGithubFg = Color(0xFFFFFFFF),
    socialButtonFacebookFill = Color(0xFF1877F2),
    socialButtonFacebookFillHover = Color(0xFF166FE5),
    socialButtonFacebookFg = Color(0xFFFFFFFF),
    socialButtonXFill = Color(0xFF000000),
    socialButtonXFillHover = Color(0xFF1C1C1E),
    socialButtonXFg = Color(0xFFFFFFFF),
    socialButtonGitlabFill = Color(0xFFFC6D26),
    socialButtonGitlabFillHover = Color(0xFFE2561A),
    socialButtonGitlabFg = Color(0xFF171321),
    videoPlayerControlFg = Color(0xFFFFFFFF),
    videoPlayerActionFillHover = Color(0x33FFFFFF),
    videoPlayerOverlayFill = Color(0x33FFFFFF),
    videoPlayerOverlayFillHover = Color(0x4DFFFFFF),
    videoPlayerTrack = Color(0x4DFFFFFF),
    videoPlayerTrackBuffer = Color(0x80FFFFFF),
    videoPlayerTooltipFill = Color(0xCC000000),
)

object DsFontWeight {
    val regular = FontWeight(400)
    val medium = FontWeight(500)
    val semibold = FontWeight(600)
    val bold = FontWeight(700)
}

object DsFontSize {
    val displayLg = 60.sp
    val displayMd = 48.sp
    val displaySm = 36.sp
    val headingXl = 30.sp
    val headingLg = 24.sp
    val headingMd = 20.sp
    val headingSm = 18.sp
    val headingXs = 16.sp
    val bodyXl = 20.sp
    val bodyLg = 18.sp
    val bodyMd = 16.sp
    val bodySm = 14.sp
    val bodyXs = 12.sp
    val codeMd = 14.sp
    val codeSm = 12.sp
    val inputMin = 16.sp
}

object DsFontLineHeight {
    val displayLg = 72.sp
    val displayMd = 60.sp
    val displaySm = 44.sp
    val headingXl = 38.sp
    val headingLg = 32.sp
    val headingMd = 30.sp
    val headingSm = 28.sp
    val headingXs = 24.sp
    val bodyXl = 30.sp
    val bodyLg = 28.sp
    val bodyMd = 24.sp
    val bodySm = 20.sp
    val bodyXs = 18.sp
    val codeMd = 20.sp
    val codeSm = 18.sp
}

object DsFontLetterSpacing {
    val displayLg = -1.2.sp
    val displayMd = -0.96.sp
    val displaySm = -0.72.sp
    val headingXl = -0.3.sp
    val headingLg = -0.24.sp
    val headingMd = -0.2.sp
    val `default` = 0.sp
}

object DsSpace {
    val none = 0.dp
    val xxs = 2.dp
    val xs = 4.dp
    val sm = 6.dp
    val md = 8.dp
    val lg = 12.dp
    val xl = 16.dp
    val space2xl = 20.dp
    val space3xl = 24.dp
    val space4xl = 32.dp
    val space5xl = 40.dp
    val space6xl = 48.dp
    val space7xl = 64.dp
    val space8xl = 80.dp
    val space9xl = 96.dp
    val space10xl = 128.dp
    val space11xl = 160.dp
    val optical = 2.dp
}

object DsSizes {
    val controlXs = 32.dp
    val controlSm = 36.dp
    val controlMd = 40.dp
    val controlLg = 44.dp
    val controlXl = 48.dp
    val iconXs = 12.dp
    val iconSm = 16.dp
    val iconMd = 20.dp
    val iconLg = 24.dp
    val iconXl = 32.dp
    val avatar2xs = 16.dp
    val avatarXs = 24.dp
    val avatarSm = 32.dp
    val avatarMd = 40.dp
    val avatarLg = 48.dp
    val avatarXl = 56.dp
    val avatar2xl = 64.dp
    val indicatorXs = 6.dp
    val indicatorSm = 8.dp
    val indicatorMd = 10.dp
    val indicatorLg = 12.dp
    val trackSm = 4.dp
    val trackMd = 6.dp
    val trackLg = 8.dp
    val widthXxs = 320.dp
    val widthXs = 384.dp
    val widthSm = 480.dp
    val widthMd = 560.dp
    val widthLg = 640.dp
    val widthXl = 768.dp
    val width2xl = 1024.dp
    val width3xl = 1280.dp
    val width4xl = 1440.dp
    val width5xl = 1600.dp
    val width6xl = 1920.dp
    val containerMax = 1280.dp
    val containerMarginMobile = 16.dp
    val containerMarginDesktop = 32.dp
    val measureReading = 640.dp
    val touchMin = 44.dp
}

object DsRadius {
    val none = 0.dp
    val xs = 4.dp
    val sm = 6.dp
    val control = 8.dp
    val indicator = 9999.dp
    val surface = 12.dp
    val modal = 16.dp
    val full = 9999.dp
}

object DsBorderWidth {
    val `default` = 1.dp
    val strong = 2.dp
    val focus = 2.dp
    val selected = 2.dp
}

object DsComponent {
    val buttonPaddingXXs = 10.dp
    val buttonPaddingXSm = 12.dp
    val buttonPaddingXMd = 14.dp
    val buttonPaddingXLg = 16.dp
    val buttonPaddingXXl = 18.dp
    val buttonGapXs = 4.dp
    val buttonGapSm = 4.dp
    val buttonGapMd = 4.dp
    val buttonGapLg = 6.dp
    val buttonGapXl = 6.dp
    val iconButtonSizeXs = 28.dp
    val iconButtonSizeSm = 32.dp
    val iconButtonSizeMd = 36.dp
    val iconButtonSizeLg = 44.dp
    val linkGapSm = 4.dp
    val linkGapMd = 4.dp
    val linkGapLg = 6.dp
    val badgePaddingXSm = 8.dp
    val badgePaddingXMd = 10.dp
    val badgePaddingXLg = 12.dp
    val badgePaddingXTightSm = 6.dp
    val badgePaddingXTightMd = 8.dp
    val badgePaddingXTightLg = 10.dp
    val tagHeightSm = 24.dp
    val tagHeightMd = 28.dp
    val tagHeightLg = 32.dp
    val tagPaddingXMd = 10.dp
    val tagPaddingXTightSm = 4.dp
    val tagPaddingXTightMd = 4.dp
    val tagPaddingXTightLg = 6.dp
    val checkboxSizeSm = 16.dp
    val checkboxSizeMd = 20.dp
    val radioSizeSm = 16.dp
    val radioSizeMd = 20.dp
    val checkboxRadiusSm = 4.dp
    val checkboxRadiusMd = 6.dp
    val checkboxMarkSm = 12.dp
    val checkboxMarkMd = 14.dp
    val switchWidthSm = 36.dp
    val switchWidthMd = 44.dp
    val switchHeightSm = 20.dp
    val switchHeightMd = 24.dp
    val switchInset = 2.dp
    val switchThumbSm = 16.dp
    val switchThumbMd = 20.dp
    val switchSlimWidthSm = 32.dp
    val switchSlimWidthMd = 40.dp
    val switchSlimTrackSm = 10.dp
    val switchSlimTrackMd = 12.dp
    val textControlPaddingXSm = 12.dp
    val textControlPaddingXMd = 12.dp
    val textControlPaddingXLg = 14.dp
    val textControlMultilineMinHeight = 128.dp
    val textControlPaddingYMultiline = 12.dp
    val profilePhotoSizeSm = 72.dp
    val profilePhotoSizeMd = 96.dp
    val profilePhotoSizeLg = 160.dp
    val profilePhotoRingSm = 3.dp
    val profilePhotoRingMd = 4.dp
    val profilePhotoRingLg = 6.dp
    val progressRingThickness2xs = 6.dp
    val progressRingThicknessXs = 16.dp
    val progressRingThicknessSm = 16.dp
    val progressRingThicknessMd = 20.dp
    val progressRingThicknessLg = 20.dp
    val spinnerThicknessSm = 2.dp
    val spinnerThicknessMd = 2.dp
    val spinnerThicknessLg = 4.dp
    val spinnerThicknessXl = 6.dp
    val spinnerSizeXl = 48.dp
    val kbdHeightSm = 20.dp
    val kbdHeightMd = 24.dp
    val featuredIconSizeSm = 32.dp
    val featuredIconSizeMd = 40.dp
    val featuredIconSizeLg = 48.dp
    val featuredIconSizeXl = 56.dp
    val featuredIconIconXl = 28.dp
    val buttonGroupItemPaddingXSm = 12.dp
    val buttonGroupItemPaddingXMd = 16.dp
    val buttonGroupItemPaddingYSm = 8.dp
    val buttonGroupItemPaddingYMd = 8.dp
    val codeFieldCellSizeSm = 64.dp
    val codeFieldCellSizeMd = 80.dp
    val codeFieldCellSizeLg = 96.dp
    val avatarGroupOverlapXs = -4.dp
    val avatarGroupOverlapSm = -8.dp
    val avatarGroupOverlapMd = -12.dp
    val selectListMaxHeight = 320.dp
    val menuWidth = 240.dp
    val badgeGroupPaddingBadgeMd = 4.dp
    val badgeGroupPaddingMessageMd = 10.dp
    val badgeGroupPaddingBadgeLg = 4.dp
    val badgeGroupPaddingMessageLg = 10.dp
}

/** Text styles. FontFamily.Default = the platform system font; a brand font is mapped in DsTheme. */
object DsTextStyles {
    val displayLgSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 60.sp, lineHeight = 72.sp, letterSpacing = -1.2.sp, fontWeight = FontWeight(600))
    val displayLgBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 60.sp, lineHeight = 72.sp, letterSpacing = -1.2.sp, fontWeight = FontWeight(700))
    val displayMdSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 48.sp, lineHeight = 60.sp, letterSpacing = -0.96.sp, fontWeight = FontWeight(600))
    val displayMdBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 48.sp, lineHeight = 60.sp, letterSpacing = -0.96.sp, fontWeight = FontWeight(700))
    val displaySmSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 36.sp, lineHeight = 44.sp, letterSpacing = -0.72.sp, fontWeight = FontWeight(600))
    val displaySmBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 36.sp, lineHeight = 44.sp, letterSpacing = -0.72.sp, fontWeight = FontWeight(700))
    val headingXlSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 30.sp, lineHeight = 38.sp, letterSpacing = -0.3.sp, fontWeight = FontWeight(600))
    val headingXlBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 30.sp, lineHeight = 38.sp, letterSpacing = -0.3.sp, fontWeight = FontWeight(700))
    val headingLgSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 24.sp, lineHeight = 32.sp, letterSpacing = -0.24.sp, fontWeight = FontWeight(600))
    val headingLgBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 24.sp, lineHeight = 32.sp, letterSpacing = -0.24.sp, fontWeight = FontWeight(700))
    val headingMdSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 20.sp, lineHeight = 30.sp, letterSpacing = -0.2.sp, fontWeight = FontWeight(600))
    val headingMdBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 20.sp, lineHeight = 30.sp, letterSpacing = -0.2.sp, fontWeight = FontWeight(700))
    val headingSmSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 18.sp, lineHeight = 28.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val headingSmBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 18.sp, lineHeight = 28.sp, letterSpacing = 0.sp, fontWeight = FontWeight(700))
    val headingXsSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, lineHeight = 24.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val headingXsBold = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, lineHeight = 24.sp, letterSpacing = 0.sp, fontWeight = FontWeight(700))
    val bodyXlRegular = TextStyle(fontFamily = FontFamily.Default, fontSize = 20.sp, lineHeight = 30.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val bodyXlMedium = TextStyle(fontFamily = FontFamily.Default, fontSize = 20.sp, lineHeight = 30.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
    val bodyXlSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 20.sp, lineHeight = 30.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val bodyLgRegular = TextStyle(fontFamily = FontFamily.Default, fontSize = 18.sp, lineHeight = 28.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val bodyLgMedium = TextStyle(fontFamily = FontFamily.Default, fontSize = 18.sp, lineHeight = 28.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
    val bodyLgSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 18.sp, lineHeight = 28.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val bodyMdRegular = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, lineHeight = 24.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val bodyMdMedium = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, lineHeight = 24.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
    val bodyMdSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, lineHeight = 24.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val bodySmRegular = TextStyle(fontFamily = FontFamily.Default, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val bodySmMedium = TextStyle(fontFamily = FontFamily.Default, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
    val bodySmSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val bodyXsRegular = TextStyle(fontFamily = FontFamily.Default, fontSize = 12.sp, lineHeight = 18.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val bodyXsMedium = TextStyle(fontFamily = FontFamily.Default, fontSize = 12.sp, lineHeight = 18.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
    val bodyXsSemibold = TextStyle(fontFamily = FontFamily.Default, fontSize = 12.sp, lineHeight = 18.sp, letterSpacing = 0.sp, fontWeight = FontWeight(600))
    val codeMdRegular = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val codeMdMedium = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
    val codeSmRegular = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 12.sp, lineHeight = 18.sp, letterSpacing = 0.sp, fontWeight = FontWeight(400))
    val codeSmMedium = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 12.sp, lineHeight = 18.sp, letterSpacing = 0.sp, fontWeight = FontWeight(500))
}

/** One layer of an effect style. Compose draws elevation from the strongest layer; focus rings use DsInteraction. */
@Immutable
data class DsShadowLayer(val x: Float, val y: Float, val blur: Float, val spread: Float, val light: Color, val dark: Color)

object DsShadows {
    val elevationControl = listOf(DsShadowLayer(0f, 1f, 2f, 0f, Color(0x0D000000), Color(0x33000000)))
    val elevationRaised = listOf(DsShadowLayer(0f, 1f, 2f, 0f, Color(0x0D000000), Color(0x33000000)), DsShadowLayer(0f, 1f, 3f, 0f, Color(0x1A000000), Color(0x66000000)))
    val elevationOverlay = listOf(DsShadowLayer(0f, 12f, 16f, -4f, Color(0x1A000000), Color(0x66000000)), DsShadowLayer(0f, 4f, 6f, -2f, Color(0x0D000000), Color(0x33000000)))
    val elevationModal = listOf(DsShadowLayer(0f, 20f, 24f, -4f, Color(0x1A000000), Color(0x66000000)), DsShadowLayer(0f, 8f, 8f, -4f, Color(0x0D000000), Color(0x33000000)))
    val focusDefault = listOf(DsShadowLayer(0f, 0f, 0f, 4f, Color(0xFF3B82F6), Color(0xFF60A5FA)), DsShadowLayer(0f, 0f, 0f, 2f, Color(0xFFFFFFFF), Color(0xFF020617)))
    val focusDanger = listOf(DsShadowLayer(0f, 0f, 0f, 4f, Color(0xFFDC2626), Color(0xFFF87171)), DsShadowLayer(0f, 0f, 0f, 2f, Color(0xFFFFFFFF), Color(0xFF020617)))
}

/** Motion in ms; Reduced applies when the system asks for reduced motion (DsTheme reads it). */
@Immutable
data class DsMotion(
    val durationInstant: Int,
    val durationFast: Int,
    val durationBase: Int,
    val durationSlow: Int,
    val durationLoop: Int,
    val delayTooltip: Int,
    val delayToast: Int,
    val delayDebounce: Int,
)
val StandardDsMotion = DsMotion(durationInstant = 0, durationFast = 120, durationBase = 200, durationSlow = 300, durationLoop = 900, delayTooltip = 400, delayToast = 5000, delayDebounce = 250)
val ReducedDsMotion = DsMotion(durationInstant = 0, durationFast = 120, durationBase = 0, durationSlow = 0, durationLoop = 1800, delayTooltip = 400, delayToast = 5000, delayDebounce = 250)
object DsEasing {
    val easingStandard = androidx.compose.animation.core.CubicBezierEasing(0.2f, 0f, 0f, 1f)
    val easingEnter = androidx.compose.animation.core.CubicBezierEasing(0f, 0f, 0.2f, 1f)
    val easingExit = androidx.compose.animation.core.CubicBezierEasing(0.4f, 0f, 1f, 1f)
    val easingLinear = androidx.compose.animation.core.CubicBezierEasing(0f, 0f, 1f, 1f)
}
